evidencePath = fullfile('D:\CODE\deshidratador', '06_manuscript', 'article_Q1', 'review', ...
    'CURRENT_ENVIRONMENT_COMPATIBILITY_MATLAB_EVIDENCE_v96z.txt');
diary(evidencePath);
fprintf('\nCHECKPOINT = MATLAB_DIARY_ACTIVE\n');
fprintf('INSPECTION_STARTED_UTC = %s\n', char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSSXXX')));

try
    historicalMat = fullfile('D:\CODE\deshidratador', '05_runs', ...
        'triobjective_formal_ga_v96m', ...
        'TRIOBJECTIVE_FORMAL_GA_v96m_seedaware_v96z_rngfix_20260727_185506', ...
        'mat', 'TRIOBJECTIVE_FORMAL_GA_v96m_seedaware_v96z_rngfix_raw.mat');

    fprintf('CHECKPOINT = METADATA_BEGIN\n');
    fprintf('VERSION = %s\n', version);
    fprintf('RELEASE = %s\n', version('-release'));
    fprintf('COMPUTER = %s\n', computer);
    globalOptimInfo = ver('globaloptim');
    fprintf('GLOBAL_OPTIM_COUNT = %d\n', numel(globalOptimInfo));
    disp(globalOptimInfo);
    fprintf('CHECKPOINT = METADATA_COMPLETE\n');

    fprintf('HISTORICAL_MAT = %s\n', historicalMat);
    fprintf('CHECKPOINT = WHOS_HISTORICAL_MAT_BEGIN\n');
    historicalWhos = whos('-file', historicalMat);
    disp(historicalWhos);
    fprintf('WHOS_HAS_OPTS = %d\n', any(strcmp({historicalWhos.name}, 'opts')));
    fprintf('CHECKPOINT = WHOS_HISTORICAL_MAT_COMPLETE\n');

    fprintf('CHECKPOINT = LOAD_OPTS_ONLY_BEGIN\n');
    S = load(historicalMat, 'opts');
    opts_historical = S.opts;
    clear S;
    fprintf('HISTORICAL_OPTS_CLASS = %s\n', class(opts_historical));
    fprintf('HISTORICAL_OPTS_DISPLAY_BEGIN\n');
    disp(opts_historical);
    fprintf('HISTORICAL_OPTS_DISPLAY_END\n');
    fprintf('HISTORICAL_PROPERTIES_BEGIN\n');
    disp(properties(opts_historical));
    fprintf('HISTORICAL_PROPERTIES_END\n');
    fprintf('CHECKPOINT = LOAD_OPTS_ONLY_COMPLETE\n');

    fprintf('CHECKPOINT = CURRENT_DEFAULT_OPTIONS_BEGIN\n');
    opts_current_default = optimoptions('gamultiobj');
    fprintf('CURRENT_DEFAULT_OPTS_CLASS = %s\n', class(opts_current_default));
    fprintf('CURRENT_DEFAULT_OPTS_DISPLAY_BEGIN\n');
    disp(opts_current_default);
    fprintf('CURRENT_DEFAULT_OPTS_DISPLAY_END\n');
    fprintf('CURRENT_DEFAULT_PROPERTIES_BEGIN\n');
    disp(properties(opts_current_default));
    fprintf('CURRENT_DEFAULT_PROPERTIES_END\n');
    fprintf('CHECKPOINT = CURRENT_DEFAULT_OPTIONS_COMPLETE\n');

    labels = { ...
        'ParetoFraction'; ...
        'DistanceMeasureFcn'; ...
        'SelectionFcn'; ...
        'CreationFcn'; ...
        'CrossoverFcn'; ...
        'MutationFcn'; ...
        'CrossoverFraction'; ...
        'MaxStallGenerations'; ...
        'PopulationSize'; ...
        'MaxGenerations'; ...
        'FunctionTolerance'; ...
        'ConstraintTolerance'; ...
        'UseParallel'; ...
        'PlotFcn'; ...
        'InitialPopulationMatrix'; ...
        'InitialScores'; ...
        'InitialPopulationRange'; ...
        'PopulationType'; ...
        'MigrationDirection'; ...
        'MigrationFraction'; ...
        'MigrationInterval'; ...
        'HybridFcn'; ...
        'OutputFcn'; ...
        'PlotInterval'; ...
        'MaxTime'; ...
        'UseVectorized'; ...
        'IntegerTolerance'; ...
        'Display'};

    aliases = { ...
        {'ParetoFraction'}; ...
        {'DistanceMeasureFcn'}; ...
        {'SelectionFcn'}; ...
        {'CreationFcn'}; ...
        {'CrossoverFcn'}; ...
        {'MutationFcn'}; ...
        {'CrossoverFraction'}; ...
        {'MaxStallGenerations', 'StallGenLimit'}; ...
        {'PopulationSize'}; ...
        {'MaxGenerations', 'Generations'}; ...
        {'FunctionTolerance', 'TolFunValue'}; ...
        {'ConstraintTolerance', 'TolCon'}; ...
        {'UseParallel'}; ...
        {'PlotFcn', 'PlotFcns'}; ...
        {'InitialPopulationMatrix', 'InitialPopulation'}; ...
        {'InitialScoresMatrix', 'InitialScores'}; ...
        {'InitialPopulationRange', 'PopInitRange'}; ...
        {'PopulationType'}; ...
        {'MigrationDirection'}; ...
        {'MigrationFraction'}; ...
        {'MigrationInterval'}; ...
        {'HybridFcn'}; ...
        {'OutputFcn', 'OutputFcns'}; ...
        {'PlotInterval'}; ...
        {'MaxTime', 'TimeLimit'}; ...
        {'UseVectorized', 'Vectorized'}; ...
        {'IntegerTolerance'}; ...
        {'Display'}};

    fprintf('CHECKPOINT = PROPERTY_COMPARISON_BEGIN\n');
    allEqual = true;
    for k = 1:numel(labels)
        [historicalName, historicalValue, historicalFound] = readAliasedProperty(opts_historical, aliases{k});
        [currentName, currentValue, currentFound] = readAliasedProperty(opts_current_default, aliases{k});
        equalValue = historicalFound && currentFound && isequaln(historicalValue, currentValue);
        allEqual = allEqual && equalValue;
        fprintf('COMPARE|%s|historical_property=%s|current_property=%s|historical_found=%d|current_found=%d|equal=%d\n', ...
            labels{k}, historicalName, currentName, historicalFound, currentFound, equalValue);
        fprintf('HISTORICAL_VALUE|%s\n', labels{k});
        disp(historicalValue);
        fprintf('CURRENT_DEFAULT_VALUE|%s\n', labels{k});
        disp(currentValue);
    end
    fprintf('ALL_INSPECTED_PROPERTIES_EQUAL = %d\n', allEqual);
    fprintf('CHECKPOINT = PROPERTY_COMPARISON_COMPLETE\n');
    fprintf('GAMULTIOBJ_EXECUTED = NO\n');
    fprintf('MODEL_EVALUATED = NO\n');
    fprintf('OBJECTIVE_EVALUATED = NO\n');
    fprintf('CORRECTED_R1_EXECUTED = NO\n');
    fprintf('MATLAB_INSPECTION_COMPLETED = YES\n');
    fprintf('INSPECTION_STATUS = COMPLETE\n');
catch ME
    fprintf('INSPECTION_STATUS = ERROR\n');
    fprintf('ERROR_IDENTIFIER = %s\n', ME.identifier);
    fprintf('ERROR_MESSAGE = %s\n', ME.message);
    fprintf('ERROR_REPORT_BEGIN\n%s\nERROR_REPORT_END\n', getReport(ME, 'extended', 'hyperlinks', 'off'));
end

fprintf('INSPECTION_FINISHED_UTC = %s\n', char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSSXXX')));
fprintf('CHECKPOINT = MATLAB_DIARY_CLOSING\n');
diary off;

function [name, value, found] = readAliasedProperty(optionsObject, candidates)
    objectProperties = properties(optionsObject);
    name = '<missing>';
    value = [];
    found = false;
    for idx = 1:numel(candidates)
        if any(strcmp(objectProperties, candidates{idx}))
            name = candidates{idx};
            value = optionsObject.(name);
            found = true;
            return;
        end
    end
end
