function createfigure1(X1, YMatrix1)
%CREATEFIGURE1(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 25-Jan-2024 19:48:37

% Create figure
figure1 = figure('NumberTitle','off','Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,...
    'MarkerIndices',[1 6 11 16 21 26 31 36 41 46 51 56 61],...
    'Color',[0 0 0]);
set(plot1(1),'DisplayName','XR{\it @0.5kg/s}');
set(plot1(2),'DisplayName','XR{\it @1.03kg/s}','LineWidth',2,...
    'LineStyle',':');
set(plot1(3),'DisplayName','XR{\it @1.80kg/s}','LineStyle','--');

% Create ylabel
ylabel('XR [adim]');

% Create xlabel
xlabel('Time [h]');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'LineWidth',1.5);
% Create legend
legend(axes1,'show');

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.536458333333333 0.504366197183099 0.263854166666666 0.379827856025039]);
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix1,...
    'MarkerIndices',[1 6 11 16 21 26 31 36 41 46 51 56 61],...
    'Color',[0 0 0]);
set(plot2(1),'DisplayName','XR{\it @0.5kg/s}');
set(plot2(2),'DisplayName','XR{\it @1.03kg/s}','LineWidth',2,...
    'LineStyle',':');
set(plot2(3),'DisplayName','XR{\it @1.80kg/s}','LineStyle','--');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[16.0026743111722 17]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0.299350250193072 0.399497585457006]);
box(axes2,'on');
grid(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'LineWidth',1.5);
% Create rectangle
annotation(figure1,'rectangle',...
    [0.776520833333333 0.21283255086072 0.1286875 0.0985915492957747]);

