function out = create_solar_tmax_fix_v621()
% CREATE_SOLAR_TMAX_FIX_v621
% Crea:
%   1) opt_tunel_mod2_v11_solar_tmax_closure_fixed.m
%   2) objective_productive_corrected_v621_solarfix.m
%
% No modifica v10.
% No modifica objective v611.
% No repite el AG.
%
% Uso:
%   out = create_solar_tmax_fix_v621();

    rootDir = setup_v05_paths();
    addpath(genpath(fullfile(rootDir,'02_src_limpio')));
    rehash;

    wrappersDir   = fullfile(rootDir,'02_src_limpio','wrappers');
    productionDir = fullfile(rootDir,'02_src_limpio','production');

    srcWrapper = fullfile(wrappersDir,'opt_tunel_mod2_v10_energy_mode_corrected.m');
    dstWrapper = fullfile(wrappersDir,'opt_tunel_mod2_v11_solar_tmax_closure_fixed.m');

    dstObjective = fullfile(productionDir,'objective_productive_corrected_v621_solarfix.m');

    if ~isfile(srcWrapper)
        error('No existe el wrapper fuente: %s', srcWrapper);
    end

    txt = fileread(srcWrapper);

    % ---------------------------------------------------------------------
    % 1) Cambiar firma de función
    % ---------------------------------------------------------------------
    oldSignature = ...
        'function [Q_aux_tot, dry_time, M_prod_fin, MR_fin, Irradiacion, irr_diag] = opt_tunel_mod2_v10_energy_mode_corrected(m_max,T_min,r_div2,t_rec_ini, W0, m_i, Mi, mwi, md, m_f, Mf, mwf, M_des, mode_operation)';

    newSignature = ...
        'function [Q_aux_tot, dry_time, M_prod_fin, MR_fin, Irradiacion, irr_diag] = opt_tunel_mod2_v11_solar_tmax_closure_fixed(m_max,T_min,r_div2,t_rec_ini, W0, m_i, Mi, mwi, md, m_f, Mf, mwf, M_des, mode_operation)';

    if ~contains(txt, oldSignature)
        error('No se encontró la firma esperada de v10. Revisar manualmente la primera línea del wrapper.');
    end

    txt = strrep(txt, oldSignature, newSignature);

    % ---------------------------------------------------------------------
    % 2) Corregir cierre por t_max sin regexprep con contador
    % ---------------------------------------------------------------------
    oldPattern = [
        '    if t\(i\)>=\(t_max-t_step\)\*3600\s*' ...
        'Q_aux_tot=sum\(Q_aux\*t_step\*3600\)/1000;\s*' ...
        'Irradiacion=sum\(I\*t_step\*3600\*A_cap\*8\*mean\(ETHA_capt\)\)/1e6;\s*' ...
        'dry_time=t\(i\)/3600-t_ini;\s*' ...
        'M_prod_fin=min\(M_prod\);\s*' ...
        'MR_fin=MR\(end-1\);\s*' ...
        'break\s*' ...
        'end'
    ];

    newBlock = sprintf([ ...
        '    if t(i)>=(t_max-t_step)*3600\n' ...
        '        Q_aux_tot=sum(Q_aux*t_step*3600)/1000;\n' ...
        '        Irradiacion=sum(I*t_step*3600*A_cap*8*mean(ETHA_capt))/1e6;\n' ...
        '        dry_time=t(i)/3600-t_ini;\n' ...
        '\n' ...
        '        %% SOLAR-TMAX-CLOSURE-FIX-001\n' ...
        '        %% Usar el ultimo estado fisico valido, no min(M_prod) ni MR(end-1).\n' ...
        '        M_prod_fin=M_prod(i);\n' ...
        '        MR_fin=MR(i);\n' ...
        '\n' ...
        '        if exist(''irr_diag'',''var'')\n' ...
        '            irr_diag.termination_status = "TMAX_REACHED";\n' ...
        '            irr_diag.tmax_closure_fix = "M_prod_fin=M_prod(i); MR_fin=MR(i)";\n' ...
        '        end\n' ...
        '\n' ...
        '        break\n' ...
        '    end' ...
    ]);

    [s,e] = regexp(txt, oldPattern, 'start', 'end');

    if numel(s) ~= 1
        error('No se encontró exactamente una vez el bloque t_max esperado. Coincidencias encontradas: %d. No se creó v11 para evitar parche incorrecto.', numel(s));
    end

    txt = [txt(1:s-1), newBlock, txt(e+1:end)];

    fid = fopen(dstWrapper,'w');
    if fid < 0
        error('No se pudo crear: %s', dstWrapper);
    end
    fwrite(fid, txt);
    fclose(fid);

    % ---------------------------------------------------------------------
    % 3) Crear función objetivo temporal v621
    % ---------------------------------------------------------------------
    objectiveText = sprintf([ ...
        'function [f, detail] = objective_productive_corrected_v621_solarfix(x, mode_operation)\n' ...
        '%% OBJECTIVE_PRODUCTIVE_CORRECTED_v621_SOLARFIX\n' ...
        '%% Igual que objective_productive_corrected_v611, pero llama al wrapper v11.\n' ...
        '%% Uso exclusivo para validar SOLAR-TMAX-CLOSURE-FIX-001.\n' ...
        '%% No usar para repetir AG todavía.\n' ...
        '\n' ...
        '    if nargin < 2 || isempty(mode_operation)\n' ...
        '        mode_operation = "hybrid";\n' ...
        '    end\n' ...
        '\n' ...
        '    mode_operation = string(mode_operation);\n' ...
        '\n' ...
        '    W0  = 0.75;\n' ...
        '    m_i = 20;\n' ...
        '    Mi  = 6.55;\n' ...
        '    mwi = 17.35;\n' ...
        '    md  = 2.65;\n' ...
        '    m_f = 2.913;\n' ...
        '    Mf  = 0.10;\n' ...
        '    mwf = 0.263;\n' ...
        '    M_des = 0.10;\n' ...
        '\n' ...
        '    m_max     = x(1);\n' ...
        '    T_min     = x(2);\n' ...
        '    r_div2    = x(3);\n' ...
        '    t_rec_ini = x(4);\n' ...
        '\n' ...
        '    [Q_aux_tot, dry_time, M, MR, Irradiacion, irr_diag] = ...\n' ...
        '        opt_tunel_mod2_v11_solar_tmax_closure_fixed( ...\n' ...
        '            m_max,T_min,r_div2,t_rec_ini, ...\n' ...
        '            W0,m_i,Mi,mwi,md,m_f,Mf,mwf,M_des,mode_operation);\n' ...
        '\n' ...
        '    cost_params = build_cost_params_historical();\n' ...
        '    cost = calc_cost_breakdown(Q_aux_tot, Irradiacion, dry_time, md, Mi, M, cost_params);\n' ...
        '\n' ...
        '    f = [MR, cost.cost_specific_USD_per_kgwater];\n' ...
        '\n' ...
        '    detail = struct();\n' ...
        '    detail.status = ''OK'';\n' ...
        '    detail.mode_operation = char(mode_operation);\n' ...
        '    detail.Q_aux_tot = Q_aux_tot;\n' ...
        '    detail.Irradiacion = Irradiacion;\n' ...
        '    detail.dry_time = dry_time;\n' ...
        '    detail.M = M;\n' ...
        '    detail.MR = MR;\n' ...
        '    detail.cost = cost;\n' ...
        '    detail.irr_diag = irr_diag;\n' ...
        '\n' ...
        '    if isfield(irr_diag,''rule'')\n' ...
        '        detail.irradiance_rule = irr_diag.rule;\n' ...
        '    end\n' ...
        '\n' ...
        '    if isfield(irr_diag,''aux_rule'')\n' ...
        '        detail.aux_rule = irr_diag.aux_rule;\n' ...
        '    end\n' ...
        '\n' ...
        '    if isfield(irr_diag,''termination_status'')\n' ...
        '        detail.termination_status = irr_diag.termination_status;\n' ...
        '    else\n' ...
        '        detail.termination_status = "UNKNOWN";\n' ...
        '    end\n' ...
        'end\n' ...
    ]);

    fid = fopen(dstObjective,'w');
    if fid < 0
        error('No se pudo crear: %s', dstObjective);
    end
    fwrite(fid, objectiveText);
    fclose(fid);

    rehash;

    out = struct();
    out.status = 'SOLAR_TMAX_FIX_FILES_CREATED';
    out.wrapper_v11 = dstWrapper;
    out.objective_v621 = dstObjective;
    out.which_wrapper_v11 = which('opt_tunel_mod2_v11_solar_tmax_closure_fixed');
    out.which_objective_v621 = which('objective_productive_corrected_v621_solarfix');

    disp('=== CREATE_SOLAR_TMAX_FIX_v621 ===')
    disp(out.status)
    disp('=== CREATED FILES ===')
    disp(out.wrapper_v11)
    disp(out.objective_v621)
    disp('=== WHICH CHECK ===')
    disp(out.which_wrapper_v11)
    disp(out.which_objective_v621)
end