function fixout = fix_gaopts_audit_extract_source_v96z_f1()
% FIX_GAOPTS_AUDIT_EXTRACT_SOURCE_v96z_f1
%
% Corrige la auditoría GAOPTS para extraer lb/ub y parámetros de opts
% desde el código fuente cuando confirm_execute=false no devuelve opts/lb/ub.
%
% No ejecuta GA.
% No ejecuta gamultiobj.
% No modifica v96m original.
% Modifica únicamente audit_gaopts_v96z_before_formal_run.m con backup.

    rootDir = setup_v05_paths();
    addpath(genpath(fullfile(rootDir,'02_src_limpio')));
    rehash;

    productionDir = fullfile(rootDir,'02_src_limpio','production');
    articleRoot = fullfile(rootDir,'06_manuscript','article_Q1');
    traceDir = fullfile(articleRoot,'traceability');
    tablesDir = fullfile(articleRoot,'tables');

    if ~isfolder(traceDir), mkdir(traceDir); end
    if ~isfolder(tablesDir), mkdir(tablesDir); end

    auditPath = fullfile(productionDir,'audit_gaopts_v96z_before_formal_run.m');

    if ~isfile(auditPath)
        error('No existe auditPath: %s', auditPath);
    end

    timestamp = datestr(now,'yyyymmdd_HHMMSS');
    backupPath = fullfile(productionDir, ...
        ['audit_gaopts_v96z_before_formal_run_BACKUP_BEFORE_SOURCE_EXTRACT_' timestamp '.m']);

    copyfile(auditPath,backupPath);

    txt = string(fileread(auditPath));

    oldBlock = [
"    % ---------------------------------------------------------------------" newline ...
"    % Obtener opts/lb/ub/nvars sin ejecutar GA" newline ...
"    % Llamar confirm_execute=false solo si el clon ya fue validado como guardado." newline ...
"    % Esta llamada puede hacer preflight interno, pero no gamultiobj." newline ...
"    % ---------------------------------------------------------------------" newline ...
"    formalPreview = [];" newline ...
"    previewStatus = ""NOT_EXECUTED"";" newline ...
"    previewError = """";" newline ...
"    opts = [];" newline ...
"    lb = [];" newline ...
"    ub = [];" newline ...
"    nvars = NaN;" newline ...
"    modeFormal = """";" newline ...
"    formalFlags = struct();" newline ...
newline ...
"    try" newline ...
"        formalPreview = run_guarded_triobjective_formal_ga_v96m_seedaware_v96z_rngfix(false, 61001);" newline ...
"        previewStatus = ""OK"";" newline ...
newline ...
"        if isfield(formalPreview,'opts')" newline ...
"            opts = formalPreview.opts;" newline ...
"        end" newline ...
newline ...
"        if isfield(formalPreview,'lb')" newline ...
"            lb = formalPreview.lb;" newline ...
"        end" newline ...
newline ...
"        if isfield(formalPreview,'ub')" newline ...
"            ub = formalPreview.ub;" newline ...
"        end" newline ...
newline ...
"        if isfield(formalPreview,'nvars')" newline ...
"            nvars = formalPreview.nvars;" newline ...
"        elseif ~isempty(lb)" newline ...
"            nvars = numel(lb);" newline ...
"        end" newline ...
newline ...
"        if isfield(formalPreview,'modeFormal')" newline ...
"            modeFormal = string(formalPreview.modeFormal);" newline ...
"        end" newline ...
newline ...
"        if isfield(formalPreview,'formalFlags')" newline ...
"            formalFlags = formalPreview.formalFlags;" newline ...
"        end" newline ...
newline ...
"    catch ME" newline ...
"        previewStatus = ""ERROR"";" newline ...
"        previewError = string(ME.message);" newline ...
"    end" newline];

    newBlock = [
"    % ---------------------------------------------------------------------" newline ...
"    % Obtener opts/lb/ub/nvars sin ejecutar GA" newline ...
"    % Primero intenta preview confirm_execute=false." newline ...
"    % Si preview no expone opts/lb/ub, extrae valores desde código fuente." newline ...
"    % ---------------------------------------------------------------------" newline ...
"    formalPreview = [];" newline ...
"    previewStatus = ""NOT_EXECUTED"";" newline ...
"    previewError = """";" newline ...
"    opts = [];" newline ...
"    lb = [];" newline ...
"    ub = [];" newline ...
"    nvars = NaN;" newline ...
"    modeFormal = """";" newline ...
"    formalFlags = struct();" newline ...
"    sourceExtract = struct();" newline ...
"    sourceExtract.used = false;" newline ...
"    sourceExtract.lb_raw = """";" newline ...
"    sourceExtract.ub_raw = """";" newline ...
"    sourceExtract.opts_raw = """";" newline ...
newline ...
"    try" newline ...
"        formalPreview = run_guarded_triobjective_formal_ga_v96m_seedaware_v96z_rngfix(false, 61001);" newline ...
"        previewStatus = ""OK"";" newline ...
newline ...
"        if isfield(formalPreview,'opts')" newline ...
"            opts = formalPreview.opts;" newline ...
"        end" newline ...
newline ...
"        if isfield(formalPreview,'lb')" newline ...
"            lb = formalPreview.lb;" newline ...
"        end" newline ...
newline ...
"        if isfield(formalPreview,'ub')" newline ...
"            ub = formalPreview.ub;" newline ...
"        end" newline ...
newline ...
"        if isfield(formalPreview,'nvars')" newline ...
"            nvars = formalPreview.nvars;" newline ...
"        elseif ~isempty(lb)" newline ...
"            nvars = numel(lb);" newline ...
"        end" newline ...
newline ...
"        if isfield(formalPreview,'modeFormal')" newline ...
"            modeFormal = string(formalPreview.modeFormal);" newline ...
"        end" newline ...
newline ...
"        if isfield(formalPreview,'formalFlags')" newline ...
"            formalFlags = formalPreview.formalFlags;" newline ...
"        end" newline ...
newline ...
"    catch ME" newline ...
"        previewStatus = ""ERROR"";" newline ...
"        previewError = string(ME.message);" newline ...
"    end" newline ...
newline ...
"    if isempty(lb) || isempty(ub)" newline ...
"        [lb_src, lb_raw] = extract_vector_assignment(seedawareTxt,""lb"");" newline ...
"        [ub_src, ub_raw] = extract_vector_assignment(seedawareTxt,""ub"");" newline ...
"        if ~isempty(lb_src)" newline ...
"            lb = lb_src;" newline ...
"            sourceExtract.used = true;" newline ...
"            sourceExtract.lb_raw = lb_raw;" newline ...
"        end" newline ...
"        if ~isempty(ub_src)" newline ...
"            ub = ub_src;" newline ...
"            sourceExtract.used = true;" newline ...
"            sourceExtract.ub_raw = ub_raw;" newline ...
"        end" newline ...
"        if ~isempty(lb)" newline ...
"            nvars = numel(lb);" newline ...
"        end" newline ...
"    end" newline ...
newline ...
"    if isempty(modeFormal)" newline ...
"        modeFormal_src = extract_string_assignment(seedawareTxt,""modeFormal"");" newline ...
"        if strlength(modeFormal_src) > 0" newline ...
"            modeFormal = modeFormal_src;" newline ...
"        end" newline ...
"    end" newline];

    if ~contains(txt, oldBlock)
        error('No se encontró el bloque esperado en audit_gaopts_v96z_before_formal_run.m. No se modifica.');
    end

    txt2 = replace(txt, oldBlock, newBlock);

    insertBefore = "function x = extract_numeric_assignment(txt,varName)";
    helperBlock = [
"function [v, raw] = extract_vector_assignment(txt,varName)" newline ...
"    v = [];" newline ...
"    raw = """";" newline ...
"    pat = varName + ""\s*=\s*\[([^\]]+)\]\s*;"";" newline ...
"    tok = regexp(txt,pat,'tokens','once');" newline ...
"    if isempty(tok)" newline ...
"        return;" newline ...
"    end" newline ...
"    raw = string(tok{1});" newline ...
"    cleaned = replace(raw,"","" ,"" "");" newline ...
"    nums = regexp(cleaned,""[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?"",'match');" newline ...
"    if isempty(nums)" newline ...
"        return;" newline ...
"    end" newline ...
"    v = str2double(nums);" newline ...
"end" newline ...
newline ...
"function s = extract_string_assignment(txt,varName)" newline ...
"    s = """";" newline ...
"    pat1 = varName + ""\s*=\s*""""([^""""]+)""""\s*;"";" newline ...
"    tok = regexp(txt,pat1,'tokens','once');" newline ...
"    if ~isempty(tok)" newline ...
"        s = string(tok{1});" newline ...
"        return;" newline ...
"    end" newline ...
"    pat2 = varName + ""\s*=\s*'([^'']+)'\s*;"";" newline ...
"    tok = regexp(txt,pat2,'tokens','once');" newline ...
"    if ~isempty(tok)" newline ...
"        s = string(tok{1});" newline ...
"    end" newline ...
"end" newline ...
newline];

    if ~contains(txt2, "function [v, raw] = extract_vector_assignment")
        txt2 = replace(txt2, insertBefore, helperBlock + insertBefore);
    end

    fid = fopen(auditPath,'w');
    if fid < 0
        error('No se pudo escribir auditPath: %s', auditPath);
    end
    fprintf(fid,'%s',txt2);
    fclose(fid);

    fixedTxt = string(fileread(auditPath));

    checks = {};
    checks{end+1,1} = check_row("F1_01","Audit file exists",isfile(auditPath),string(auditPath));
    checks{end+1,1} = check_row("F1_02","Backup created",isfile(backupPath),string(backupPath));
    checks{end+1,1} = check_row("F1_03","Source extraction block inserted",contains(fixedTxt,"sourceExtract.used"),"sourceExtract present.");
    checks{end+1,1} = check_row("F1_04","Vector extractor inserted",contains(fixedTxt,"extract_vector_assignment"),"extract_vector_assignment present.");
    checks{end+1,1} = check_row("F1_05","String extractor inserted",contains(fixedTxt,"extract_string_assignment"),"extract_string_assignment present.");
    checks{end+1,1} = check_row("F1_06","No GA executed",true,"No gamultiobj call.");
    checks{end+1,1} = check_row("F1_07","Original v96m not modified",true,"Only audit script patched.");

    Tchecks = struct2table(vertcat(checks{:}));

    if all(Tchecks.pass)
        diagnosis = "GAOPTS_AUDIT_SOURCE_EXTRACT_FIX_PASS";
        decision = "RERUN_GAOPTS_AUDIT";
        next_step = "audit = audit_gaopts_v96z_before_formal_run();";
    else
        diagnosis = "GAOPTS_AUDIT_SOURCE_EXTRACT_FIX_REQUIRES_REVIEW";
        decision = "DO_NOT_RERUN_FORMAL";
        next_step = "Inspect failed fix checks.";
    end

    checksCsv = fullfile(tablesDir,'fix_gaopts_audit_extract_source_v96z_f1_checks.csv');
    writetable(Tchecks,checksCsv);

    outMat = fullfile(traceDir,'FIX_GAOPTS_AUDIT_EXTRACT_SOURCE_v96z_f1.mat');
    save(outMat,'diagnosis','decision','next_step','auditPath','backupPath','Tchecks','checksCsv','outMat');

    fixout = struct();
    fixout.status = 'FIX_GAOPTS_AUDIT_EXTRACT_SOURCE_v96z_f1_COMPLETED';
    fixout.diagnosis = diagnosis;
    fixout.decision = decision;
    fixout.next_step = next_step;
    fixout.auditPath = auditPath;
    fixout.backupPath = backupPath;
    fixout.Tchecks = Tchecks;
    fixout.outMat = outMat;

    disp('=== FIX_GAOPTS_AUDIT_EXTRACT_SOURCE_v96z_f1 ===')
    disp(fixout.status)
    disp('=== DIAGNOSIS ===')
    disp(fixout.diagnosis)
    disp('=== DECISION ===')
    disp(fixout.decision)
    disp('=== NEXT STEP ===')
    disp(fixout.next_step)
    disp('=== CHECKS ===')
    disp(fixout.Tchecks)

end

function row = check_row(id, checkName, passVal, evidence)
    row = struct();
    row.id = string(id);
    row.check = string(checkName);
    row.pass = logical(passVal);
    row.evidence = string(evidence);
end