function fixout = fix_triobjective_CO2_objective_v96j_b()
% FIX_TRIOBJECTIVE_CO2_OBJECTIVE_v96j_b
% 9.6j-b — FIX-TRIOBJECTIVE-CO2-OBJECTIVE-v96j-001
%
% Objetivo:
%   Corregir la implementación triobjetivo fallida v96j.
%
% Problema detectado en 9.6j:
%   objective_productive_corrected_v96j_triobjective_CO2 falló con:
%       Unrecognized function or variable 'penalty_CO2'
%
% Estrategia de corrección:
%   Crear una nueva función estable:
%
%       objective_productive_corrected_v96j_triobjective_CO2_fix1
%
%   Esta función:
%       - llama a v95j validada;
%       - conserva f(1)=MR y f(2)=costo de v95j;
%       - calcula f(3)=CO2_specific_kgCO2_per_kgwater;
%       - penaliza invalidaciones con [1000, 1e6, 1e6];
%       - no modifica v10/v17/v628b/v18/v95j;
%       - no ejecuta gamultiobj.
%
% Uso:
%   fixout = fix_triobjective_CO2_objective_v96j_b();

    rootDir = setup_v05_paths();
    addpath(genpath(fullfile(rootDir,'02_src_limpio')));
    rehash;

    % ---------------------------------------------------------------------
    % Archivos
    % ---------------------------------------------------------------------
    objective_v95j = fullfile(rootDir,'02_src_limpio','production','objective_productive_corrected_v95j_endpoint_TMAX_corrected.m');
    objective_v96j_bad = fullfile(rootDir,'02_src_limpio','production','objective_productive_corrected_v96j_triobjective_CO2.m');
    objective_v96j_fix1 = fullfile(rootDir,'02_src_limpio','production','objective_productive_corrected_v96j_triobjective_CO2_fix1.m');

    wrapper_v10 = fullfile(rootDir,'02_src_limpio','wrappers','opt_tunel_mod2_v10_energy_mode_corrected.m');
    wrapper_v17 = fullfile(rootDir,'02_src_limpio','wrappers','opt_tunel_mod2_v17_nonphysical_penalty.m');
    wrapper_v18 = fullfile(rootDir,'02_src_limpio','wrappers','opt_tunel_mod2_v18_endpoint_TMAX_corrected.m');
    objective_v628b = fullfile(rootDir,'02_src_limpio','production','objective_productive_corrected_v628b_nonphysical_penalty.m');

    if ~isfile(objective_v95j)
        error('No existe objective v95j: %s', objective_v95j);
    end

    if ~isfile(objective_v96j_bad)
        error('No existe objective v96j fallida: %s', objective_v96j_bad);
    end

    % ---------------------------------------------------------------------
    % Carpeta de salida
    % ---------------------------------------------------------------------
    timestamp = datestr(now,'yyyymmdd_HHMMSS');

    fixBaseDir = fullfile(rootDir,'05_runs','triobjective_CO2_objective_fix_v96j_b');
    fixDir = fullfile(fixBaseDir,['TRIOBJECTIVE_CO2_OBJECTIVE_FIX_v96j_b_' timestamp]);

    logsDir = fullfile(fixDir,'logs');
    tablesDir = fullfile(fixDir,'tables');
    matDir = fullfile(fixDir,'mat');

    if ~isfolder(fixBaseDir), mkdir(fixBaseDir); end
    if ~isfolder(fixDir), mkdir(fixDir); end
    if ~isfolder(logsDir), mkdir(logsDir); end
    if ~isfolder(tablesDir), mkdir(tablesDir); end
    if ~isfolder(matDir), mkdir(matDir); end

    % ---------------------------------------------------------------------
    % Crear objective fix1 como wrapper objetivo estable
    % ---------------------------------------------------------------------
    code = [
"function [f, detail] = objective_productive_corrected_v96j_triobjective_CO2_fix1(x, mode_operation)" newline ...
"% OBJECTIVE_PRODUCTIVE_CORRECTED_v96j_TRIOBJECTIVE_CO2_FIX1" newline ...
"%" newline ...
"% Función objetivo triobjetivo estable basada en v95j:" newline ...
"%   f(1) = MR_final" newline ...
"%   f(2) = cost_specific_USD_per_kgwater" newline ...
"%   f(3) = CO2_specific_kgCO2_per_kgwater" newline ...
"%" newline ...
"% Factores de emisión provisionales para validación computacional:" newline ...
"%   EF_LPG_kgCO2_per_kWh  = 0.2270" newline ...
"%   EF_grid_kgCO2_per_kWh = 0.4380" newline ...
"%" newline ...
"% No usar estos factores como definitivos para manuscrito sin referencia." newline ...
"" newline ...
"    penalty = [1000, 1e6, 1e6];" newline ...
"    f = penalty;" newline ...
"    detail = struct();" newline ...
"    detail.status = ""UNINITIALIZED"";" newline ...
"    detail.execution_status = ""UNINITIALIZED"";" newline ...
"    detail.objective_version = ""v96j_triobjective_CO2_fix1"";" newline ...
"    detail.base_objective = ""objective_productive_corrected_v95j_endpoint_TMAX_corrected"";" newline ...
"" newline ...
"    EF_LPG_kgCO2_per_kWh = 0.2270;" newline ...
"    EF_grid_kgCO2_per_kWh = 0.4380;" newline ...
"    emission_factor_status = ""PROVISIONAL_FOR_CODE_VALIDATION"";" newline ...
"" newline ...
"    try" newline ...
"        [f_base, d_base] = objective_productive_corrected_v95j_endpoint_TMAX_corrected(x, mode_operation);" newline ...
"        f_base = double(f_base(:))';" newline ...
"    catch ME" newline ...
"        detail.status = ""BASE_OBJECTIVE_ERROR"";" newline ...
"        detail.execution_status = ""ERROR"";" newline ...
"        detail.error_message = string(ME.message);" newline ...
"        return" newline ...
"    end" newline ...
"" newline ...
"    detail = d_base;" newline ...
"    detail.objective_version = ""v96j_triobjective_CO2_fix1"";" newline ...
"    detail.base_objective = ""objective_productive_corrected_v95j_endpoint_TMAX_corrected"";" newline ...
"" newline ...
"    if numel(f_base) < 2 || any(~isfinite(f_base(1:2))) || any(~isreal(f_base(1:2)))" newline ...
"        f = penalty;" newline ...
"        detail.status = ""INVALID_BASE_OBJECTIVE"";" newline ...
"        detail.execution_status = ""PENALIZED"";" newline ...
"        detail.objectives = local_objectives_struct_v96j_fix1(f);" newline ...
"        return" newline ...
"    end" newline ...
"" newline ...
"    base_status = local_get_string_v96j_fix1(detail, {""status"",""detail_status"",""execution_status""}, ""UNKNOWN"");" newline ...
"    base_penalized = f_base(1) >= 999.999 || f_base(2) >= 999999.999 || base_status == ""INVALID_COST"" || base_status == ""NONPHYSICAL_TRAJECTORY"";" newline ...
"" newline ...
"    if base_penalized" newline ...
"        f = penalty;" newline ...
"        detail.status = base_status;" newline ...
"        detail.execution_status = ""PENALIZED_BASE_OBJECTIVE"";" newline ...
"        detail.objectives = local_objectives_struct_v96j_fix1(f);" newline ...
"        detail.CO2 = local_empty_CO2_v96j_fix1(EF_LPG_kgCO2_per_kWh, EF_grid_kgCO2_per_kWh, emission_factor_status, ""BASE_PENALIZED"");" newline ...
"        return" newline ...
"    end" newline ...
"" newline ...
"    Q_aux_tot = local_get_numeric_v96j_fix1(detail, {""outputs.Q_aux_tot"",""Q_aux_tot""}, NaN);" newline ...
"    if ~isfinite(Q_aux_tot)" newline ...
"        Q_aux_tot = NaN;" newline ...
"    end" newline ...
"" newline ...
"    water_removed_kg = NaN;" newline ...
"    mwi = local_get_numeric_v96j_fix1(detail, {""product.mwi"",""mwi""}, NaN);" newline ...
"    mwf = local_get_numeric_v96j_fix1(detail, {""product.mwf"",""mwf""}, NaN);" newline ...
"    if isfinite(mwi) && isfinite(mwf)" newline ...
"        water_removed_kg = mwi - mwf;" newline ...
"    end" newline ...
"" newline ...
"    if ~isfinite(water_removed_kg) || water_removed_kg <= 0" newline ...
"        water_removed_kg = local_get_numeric_v96j_fix1(detail, {""product.water_removed_kg"",""water_removed_kg""}, NaN);" newline ...
"    end" newline ...
"" newline ...
"    E_electricity_kWh = local_get_numeric_v96j_fix1(detail, {""cost.electricity_kWh"",""cost.electric_energy_kWh"",""electricity_kWh"",""electric_energy_kWh""}, NaN);" newline ...
"    if ~isfinite(E_electricity_kWh)" newline ...
"        E_electricity_kWh = 0;" newline ...
"        electricity_data_status = ""NOT_EXPOSED_ASSUMED_ZERO_FOR_VALIDATION"";" newline ...
"    else" newline ...
"        electricity_data_status = ""EXTRACTED_FROM_DETAIL"";" newline ...
"    end" newline ...
"" newline ...
"    CO2_LPG_kg = Q_aux_tot * EF_LPG_kgCO2_per_kWh;" newline ...
"    CO2_electricity_kg = E_electricity_kWh * EF_grid_kgCO2_per_kWh;" newline ...
"    CO2_total_kg = CO2_LPG_kg + CO2_electricity_kg;" newline ...
"    CO2_specific_kgCO2_per_kgwater = CO2_total_kg / water_removed_kg;" newline ...
"" newline ...
"    if ~isfinite(CO2_specific_kgCO2_per_kgwater) || ~isreal(CO2_specific_kgCO2_per_kgwater) || CO2_specific_kgCO2_per_kgwater < 0" newline ...
"        f = penalty;" newline ...
"        detail.status = ""INVALID_CO2"";" newline ...
"        detail.execution_status = ""PENALIZED_INVALID_CO2"";" newline ...
"        detail.objectives = local_objectives_struct_v96j_fix1(f);" newline ...
"    else" newline ...
"        f = [f_base(1), f_base(2), CO2_specific_kgCO2_per_kgwater];" newline ...
"        detail.status = ""OK"";" newline ...
"        detail.execution_status = ""OK"";" newline ...
"        detail.objectives = local_objectives_struct_v96j_fix1(f);" newline ...
"    end" newline ...
"" newline ...
"    detail.CO2 = struct();" newline ...
"    detail.CO2.EF_LPG_kgCO2_per_kWh = EF_LPG_kgCO2_per_kWh;" newline ...
"    detail.CO2.EF_grid_kgCO2_per_kWh = EF_grid_kgCO2_per_kWh;" newline ...
"    detail.CO2.emission_factor_status = emission_factor_status;" newline ...
"    detail.CO2.electricity_data_status = electricity_data_status;" newline ...
"    detail.CO2.water_removed_kg = water_removed_kg;" newline ...
"    detail.CO2.E_electricity_kWh = E_electricity_kWh;" newline ...
"    detail.CO2.CO2_LPG_kg = CO2_LPG_kg;" newline ...
"    detail.CO2.CO2_electricity_kg = CO2_electricity_kg;" newline ...
"    detail.CO2.CO2_total_kg = CO2_total_kg;" newline ...
"    detail.CO2.CO2_specific_kgCO2_per_kgwater = CO2_specific_kgCO2_per_kgwater;" newline ...
"    detail.CO2.scope = ""TRIOBJECTIVE_COMPUTATIONAL_VALIDATION_FACTORS_PROVISIONAL"";" newline ...
"" newline ...
"end" newline ...
"" newline ...
"function objectives = local_objectives_struct_v96j_fix1(f)" newline ...
"    objectives = struct();" newline ...
"    objectives.MR_final = f(1);" newline ...
"    objectives.cost_specific_USD_per_kgwater = f(2);" newline ...
"    objectives.CO2_specific_kgCO2_per_kgwater = f(3);" newline ...
"end" newline ...
"" newline ...
"function CO2 = local_empty_CO2_v96j_fix1(EF_LPG, EF_grid, factor_status, status)" newline ...
"    CO2 = struct();" newline ...
"    CO2.EF_LPG_kgCO2_per_kWh = EF_LPG;" newline ...
"    CO2.EF_grid_kgCO2_per_kWh = EF_grid;" newline ...
"    CO2.emission_factor_status = factor_status;" newline ...
"    CO2.electricity_data_status = string(status);" newline ...
"    CO2.water_removed_kg = NaN;" newline ...
"    CO2.E_electricity_kWh = NaN;" newline ...
"    CO2.CO2_LPG_kg = NaN;" newline ...
"    CO2.CO2_electricity_kg = NaN;" newline ...
"    CO2.CO2_total_kg = NaN;" newline ...
"    CO2.CO2_specific_kgCO2_per_kgwater = NaN;" newline ...
"    CO2.scope = ""PENALIZED_NO_CO2_CLAIM"";" newline ...
"end" newline ...
"" newline ...
"function val = local_get_numeric_v96j_fix1(S, paths, defaultVal)" newline ...
"    val = defaultVal;" newline ...
"    for k = 1:numel(paths)" newline ...
"        parts = split(string(paths{k}),'.');" newline ...
"        try" newline ...
"            tmp = S;" newline ...
"            ok = true;" newline ...
"            for j = 1:numel(parts)" newline ...
"                part = char(parts(j));" newline ...
"                if isstruct(tmp) && isfield(tmp, part)" newline ...
"                    tmp = tmp.(part);" newline ...
"                else" newline ...
"                    ok = false;" newline ...
"                    break" newline ...
"                end" newline ...
"            end" newline ...
"            if ok && isnumeric(tmp) && ~isempty(tmp)" newline ...
"                val = double(tmp(1));" newline ...
"                return" newline ...
"            end" newline ...
"        catch" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"" newline ...
"function val = local_get_string_v96j_fix1(S, paths, defaultVal)" newline ...
"    val = string(defaultVal);" newline ...
"    for k = 1:numel(paths)" newline ...
"        parts = split(string(paths{k}),'.');" newline ...
"        try" newline ...
"            tmp = S;" newline ...
"            ok = true;" newline ...
"            for j = 1:numel(parts)" newline ...
"                part = char(parts(j));" newline ...
"                if isstruct(tmp) && isfield(tmp, part)" newline ...
"                    tmp = tmp.(part);" newline ...
"                else" newline ...
"                    ok = false;" newline ...
"                    break" newline ...
"                end" newline ...
"            end" newline ...
"            if ok && ~isempty(tmp)" newline ...
"                val = string(tmp);" newline ...
"                return" newline ...
"            end" newline ...
"        catch" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
];

      fid = fopen(objective_v96j_fix1,'w');
    if fid < 0
        error('No se pudo crear objective fix1: %s', objective_v96j_fix1);
    end

    codeText = strjoin(code, "");
    fprintf(fid, '%s', codeText);

    fclose(fid);
    addpath(genpath(fullfile(rootDir,'02_src_limpio')));
    clear objective_productive_corrected_v96j_triobjective_CO2_fix1
    rehash;

    if exist('objective_productive_corrected_v96j_triobjective_CO2_fix1','file') ~= 2
        error('No quedó visible objective v96j fix1.');
    end

    % ---------------------------------------------------------------------
    % Evaluación directa
    % ---------------------------------------------------------------------
    x_selected = [0.0740767982118, 62.6832965028, 0.672252618341, 11.6517528081];

    modes = ["gasLP","hybrid","solar"];
    rows = {};

    for i = 1:numel(modes)
        mode = modes(i);

        [f95, d95, status95, err95] = local_eval_v95j_fixscript(x_selected, mode);
        [f96, d96, status96, err96] = local_eval_v96j_fixscript(x_selected, mode);

        rows{end+1,1} = local_eval_row_fixscript(mode, x_selected, f95, d95, status95, err95, f96, d96, status96, err96); %#ok<AGROW>
    end

    Teval = struct2table(vertcat(rows{:}));

    outEvalCsv = fullfile(tablesDir,'TRIOBJECTIVE_CO2_OBJECTIVE_FIX_v96j_b_eval.csv');
    writetable(Teval,outEvalCsv);

    gas = Teval(strcmp(string(Teval.mode),"gasLP"),:);
    hyb = Teval(strcmp(string(Teval.mode),"hybrid"),:);
    sol = Teval(strcmp(string(Teval.mode),"solar"),:);

    MR_gas_recalc = (gas.v96_M(1) - gas.v96_Mf(1)) / (gas.v96_Mi(1) - gas.v96_Mf(1));
    MR_hyb_recalc = (hyb.v96_M(1) - hyb.v96_Mf(1)) / (hyb.v96_Mi(1) - hyb.v96_Mf(1));

    MR_gas_diff = abs(gas.v96_f1(1) - MR_gas_recalc);
    MR_hyb_diff = abs(hyb.v96_f1(1) - MR_hyb_recalc);

    MR_vs_v95_gas_diff = abs(gas.v96_f1(1) - gas.v95_f1(1));
    MR_vs_v95_hyb_diff = abs(hyb.v96_f1(1) - hyb.v95_f1(1));

    cost_vs_v95_gas_diff = abs(gas.v96_f2(1) - gas.v95_f2(1));
    cost_vs_v95_hyb_diff = abs(hyb.v96_f2(1) - hyb.v95_f2(1));

    CO2_gas = gas.v96_f3(1);
    CO2_hyb = hyb.v96_f3(1);
    CO2_reduction_pct = 100 * (CO2_gas - CO2_hyb) / CO2_gas;

    solar_penalized = sol.v96_f1(1) >= 999.999 && sol.v96_f2(1) >= 999999.999 && sol.v96_f3(1) >= 999999.999;

    % ---------------------------------------------------------------------
    % Source scan
    % ---------------------------------------------------------------------
    sourceRows = {};
    sourceRows{end+1,1} = local_source_row_fixscript("objective_v96j_fix1_exists", objective_v96j_fix1, "", isfile(objective_v96j_fix1), "Objective v96j fix1 exists.");
    sourceRows{end+1,1} = local_source_row_fixscript("objective_v96j_bad_preserved", objective_v96j_bad, "", isfile(objective_v96j_bad), "Prior failed v96j preserved.");
    sourceRows{end+1,1} = local_source_row_fixscript("objective_v95j_preserved", objective_v95j, "", isfile(objective_v95j), "v95j preserved.");
    sourceRows{end+1,1} = local_source_row_fixscript("wrapper_v10_preserved", wrapper_v10, "", isfile(wrapper_v10), "v10 preserved.");
    sourceRows{end+1,1} = local_source_row_fixscript("wrapper_v17_preserved", wrapper_v17, "", isfile(wrapper_v17), "v17 preserved.");
    sourceRows{end+1,1} = local_source_row_fixscript("wrapper_v18_preserved", wrapper_v18, "", isfile(wrapper_v18), "v18 preserved.");
    sourceRows{end+1,1} = local_source_row_fixscript("objective_v628b_preserved", objective_v628b, "", isfile(objective_v628b), "v628b preserved.");
    sourceRows{end+1,1} = local_source_contains_fixscript("fix1_calls_v95j", objective_v96j_fix1, "objective_productive_corrected_v95j_endpoint_TMAX_corrected", "fix1 calls validated v95j.");
    sourceRows{end+1,1} = local_source_contains_fixscript("fix1_has_1x3_valid_f", objective_v96j_fix1, "f = [f_base(1), f_base(2), CO2_specific_kgCO2_per_kgwater];", "fix1 builds 1x3 objective.");
    sourceRows{end+1,1} = local_source_contains_fixscript("fix1_has_1x3_penalty", objective_v96j_fix1, "penalty = [1000, 1e6, 1e6];", "fix1 has 1x3 penalty.");
    sourceRows{end+1,1} = local_source_contains_fixscript("fix1_no_penalty_CO2", objective_v96j_fix1, "penalty_CO2", "Pattern penalty_CO2 should not exist.");

    Tsource = struct2table(vertcat(sourceRows{:}));

    % Invertir pass para ausencia de penalty_CO2
    idxPenalty = strcmp(string(Tsource.item),"fix1_no_penalty_CO2");
    if any(idxPenalty)
        Tsource.pass(idxPenalty) = ~Tsource.pass(idxPenalty);
        if Tsource.pass(idxPenalty)
            Tsource.evidence(idxPenalty) = "penalty_CO2 absent.";
        else
            Tsource.evidence(idxPenalty) = "penalty_CO2 still present.";
        end
    end

    outSourceCsv = fullfile(tablesDir,'TRIOBJECTIVE_CO2_OBJECTIVE_FIX_v96j_b_source_scan.csv');
    writetable(Tsource,outSourceCsv);

    % ---------------------------------------------------------------------
    % Checks
    % ---------------------------------------------------------------------
    checks = {};

    checks{end+1,1} = local_check_row_fixscript("C01","gasLP/hybrid valid 3obj", ...
        strcmp(string(gas.v96_status(1)),"OK") && strcmp(string(hyb.v96_status(1)),"OK") && gas.v96_nobj(1)==3 && hyb.v96_nobj(1)==3, ...
        sprintf("gas status=%s nobj=%d; hybrid status=%s nobj=%d", string(gas.v96_status(1)), gas.v96_nobj(1), string(hyb.v96_status(1)), hyb.v96_nobj(1)), ...
        "gasLP and hybrid must evaluate without error and return 3 objectives.");

    checks{end+1,1} = local_check_row_fixscript("C02","MR consistency", ...
        MR_gas_diff < 1e-8 && MR_hyb_diff < 1e-8 && MR_vs_v95_gas_diff < 1e-12 && MR_vs_v95_hyb_diff < 1e-12, ...
        sprintf("MR recalc diffs gas=%.12g hybrid=%.12g; vs v95j gas=%.12g hybrid=%.12g", MR_gas_diff, MR_hyb_diff, MR_vs_v95_gas_diff, MR_vs_v95_hyb_diff), ...
        "f(1) must match v95j and recalculated MR.");

    checks{end+1,1} = local_check_row_fixscript("C03","Cost consistency", ...
        cost_vs_v95_gas_diff < 1e-10 && cost_vs_v95_hyb_diff < 1e-10, ...
        sprintf("cost diffs gas=%.12g hybrid=%.12g", cost_vs_v95_gas_diff, cost_vs_v95_hyb_diff), ...
        "f(2) must match v95j cost.");

    checks{end+1,1} = local_check_row_fixscript("C04","CO2 finite positive", ...
        isfinite(CO2_gas) && isfinite(CO2_hyb) && CO2_gas >= 0 && CO2_hyb >= 0, ...
        sprintf("CO2 gas=%.12g; CO2 hybrid=%.12g", CO2_gas, CO2_hyb), ...
        "f(3) must be finite and nonnegative.");

    checks{end+1,1} = local_check_row_fixscript("C05","CO2 reduction sanity", ...
        CO2_hyb < CO2_gas, ...
        sprintf("CO2 reduction=%.12g%%", CO2_reduction_pct), ...
        "Hybrid should reduce CO2 vs gasLP for selected x under provisional factors.");

    checks{end+1,1} = local_check_row_fixscript("C06","Solar penalized", ...
        solar_penalized, ...
        sprintf("solar f=[%.12g %.12g %.12g], detail=%s", sol.v96_f1(1), sol.v96_f2(1), sol.v96_f3(1), string(sol.v96_detail_status(1))), ...
        "Solar remains penalized.");

    checks{end+1,1} = local_check_row_fixscript("C07","Source preservation", ...
        isfile(wrapper_v10) && isfile(wrapper_v17) && isfile(objective_v628b) && isfile(wrapper_v18) && isfile(objective_v95j) && isfile(objective_v96j_bad), ...
        "v10/v17/v628b/v18/v95j and prior v96j preserved.", ...
        "No protected source overwritten.");

    checks{end+1,1} = local_check_row_fixscript("C08","No penalty_CO2", ...
        local_source_pass_fixscript(Tsource,"fix1_no_penalty_CO2"), ...
        "fix1 does not contain undefined penalty_CO2.", ...
        "The previous error source must be absent.");

    Tchecks = struct2table(vertcat(checks{:}));

    outChecksCsv = fullfile(tablesDir,'TRIOBJECTIVE_CO2_OBJECTIVE_FIX_v96j_b_checks.csv');
    writetable(Tchecks,outChecksCsv);

    % ---------------------------------------------------------------------
    % Dictamen
    % ---------------------------------------------------------------------
    fixFlags = struct();
    fixFlags.objective_v96j_fix1_created = isfile(objective_v96j_fix1);
    fixFlags.prior_v96j_preserved = isfile(objective_v96j_bad);
    fixFlags.v10_preserved = isfile(wrapper_v10);
    fixFlags.v17_preserved = isfile(wrapper_v17);
    fixFlags.v628b_preserved = isfile(objective_v628b);
    fixFlags.v18_preserved = isfile(wrapper_v18);
    fixFlags.v95j_preserved = isfile(objective_v95j);
    fixFlags.gasLP_valid_3obj = strcmp(string(gas.v96_status(1)),"OK") && strcmp(string(gas.v96_detail_status(1)),"OK") && gas.v96_nobj(1)==3;
    fixFlags.hybrid_valid_3obj = strcmp(string(hyb.v96_status(1)),"OK") && strcmp(string(hyb.v96_detail_status(1)),"OK") && hyb.v96_nobj(1)==3;
    fixFlags.solar_penalized_3obj = solar_penalized;
    fixFlags.MR_consistency_pass = Tchecks.pass(strcmp(string(Tchecks.id),"C02"));
    fixFlags.cost_consistency_pass = Tchecks.pass(strcmp(string(Tchecks.id),"C03"));
    fixFlags.CO2_finite_positive_pass = Tchecks.pass(strcmp(string(Tchecks.id),"C04"));
    fixFlags.CO2_reduction_sanity_pass = Tchecks.pass(strcmp(string(Tchecks.id),"C05"));
    fixFlags.no_penalty_CO2_pass = Tchecks.pass(strcmp(string(Tchecks.id),"C08"));
    fixFlags.all_fix_checks_pass = all(Tchecks.pass);
    fixFlags.emission_factors_provisional = true;
    fixFlags.no_GA_executed = true;
    fixFlags.formal_run_still_on_hold = true;
    fixFlags.triobjective_smoke_pending = true;

    if fixFlags.all_fix_checks_pass
        diagnosis = "TRIOBJECTIVE_CO2_OBJECTIVE_FIX_PASS";
    else
        diagnosis = "TRIOBJECTIVE_CO2_OBJECTIVE_FIX_REQUIRES_REVIEW";
    end

    % ---------------------------------------------------------------------
    % Salidas
    % ---------------------------------------------------------------------
    outMd = fullfile(logsDir,'TRIOBJECTIVE_CO2_OBJECTIVE_FIX_v96j_b.md');
    outTxt = fullfile(logsDir,'TRIOBJECTIVE_CO2_OBJECTIVE_FIX_v96j_b.txt');
    outMat = fullfile(matDir,'TRIOBJECTIVE_CO2_OBJECTIVE_FIX_v96j_b.mat');

    save(outMat, ...
        'diagnosis','fixFlags','Teval','Tchecks','Tsource', ...
        'MR_gas_recalc','MR_hyb_recalc','MR_gas_diff','MR_hyb_diff', ...
        'MR_vs_v95_gas_diff','MR_vs_v95_hyb_diff', ...
        'cost_vs_v95_gas_diff','cost_vs_v95_hyb_diff', ...
        'CO2_gas','CO2_hyb','CO2_reduction_pct', ...
        'objective_v96j_fix1','objective_v96j_bad','objective_v95j','wrapper_v10','wrapper_v17','wrapper_v18','objective_v628b', ...
        'fixDir','outMd','outTxt','outMat','outEvalCsv','outChecksCsv','outSourceCsv');

    fid = fopen(outMd,'w');
    fprintf(fid,'# TRIOBJECTIVE_CO2_OBJECTIVE_FIX_v96j_b\n\n');
    fprintf(fid,'Diagnóstico: `%s`\n\n', diagnosis);
    fprintf(fid,'Función corregida:\n\n```text\n%s\n```\n\n', objective_v96j_fix1);

    fprintf(fid,'## Evaluación directa\n\n');
    fprintf(fid,'| mode | v95 nobj | v96 nobj | v96 status | detail | f1 MR | f2 cost | f3 CO2 | Q_aux | water_removed | CO2 total |\n');
    fprintf(fid,'|---|---:|---:|---|---|---:|---:|---:|---:|---:|---:|\n');

    for i = 1:height(Teval)
        fprintf(fid,'| `%s` | %d | %d | `%s` | `%s` | %.12g | %.12g | %.12g | %.12g | %.12g | %.12g |\n', ...
            string(Teval.mode(i)), ...
            Teval.v95_nobj(i), ...
            Teval.v96_nobj(i), ...
            string(Teval.v96_status(i)), ...
            string(Teval.v96_detail_status(i)), ...
            Teval.v96_f1(i), ...
            Teval.v96_f2(i), ...
            Teval.v96_f3(i), ...
            Teval.v96_Q_aux_tot(i), ...
            Teval.v96_water_removed_kg(i), ...
            Teval.v96_CO2_total_kg(i));
    end

    fprintf(fid,'\n## Checks\n\n');
    fprintf(fid,'| ID | Check | Pass | Evidencia | Criterio |\n');
    fprintf(fid,'|---|---|---:|---|---|\n');

    for i = 1:height(Tchecks)
        fprintf(fid,'| `%s` | `%s` | `%d` | %s | %s |\n', ...
            string(Tchecks.id(i)), ...
            string(Tchecks.check(i)), ...
            Tchecks.pass(i), ...
            string(Tchecks.evidence(i)), ...
            string(Tchecks.criterion(i)));
    end

    fprintf(fid,'\n## Métricas clave\n\n');
    fprintf(fid,'| Métrica | Valor |\n');
    fprintf(fid,'|---|---:|\n');
    fprintf(fid,'| MR_gas_diff | %.12g |\n', MR_gas_diff);
    fprintf(fid,'| MR_hyb_diff | %.12g |\n', MR_hyb_diff);
    fprintf(fid,'| cost_vs_v95_gas_diff | %.12g |\n', cost_vs_v95_gas_diff);
    fprintf(fid,'| cost_vs_v95_hyb_diff | %.12g |\n', cost_vs_v95_hyb_diff);
    fprintf(fid,'| CO2_gas_specific | %.12g |\n', CO2_gas);
    fprintf(fid,'| CO2_hybrid_specific | %.12g |\n', CO2_hyb);
    fprintf(fid,'| CO2_reduction_pct | %.12g |\n\n', CO2_reduction_pct);

    fprintf(fid,'## Restricciones\n\n');
    fprintf(fid,'- No se ejecutó `gamultiobj`.\n');
    fprintf(fid,'- Factores de emisión provisionales.\n');
    fprintf(fid,'- La corrida formal sigue detenida.\n');
    fprintf(fid,'- Falta smoke GA triobjetivo.\n\n');

    fclose(fid);

    fid = fopen(outTxt,'w');
    fprintf(fid,'FIX-TRIOBJECTIVE-CO2-OBJECTIVE-v96j-001\n');
    fprintf(fid,'status: TRIOBJECTIVE_CO2_OBJECTIVE_FIX_COMPLETED\n');
    fprintf(fid,'diagnosis: %s\n', diagnosis);
    fprintf(fid,'objective_v96j_fix1_created: %d\n', fixFlags.objective_v96j_fix1_created);
    fprintf(fid,'prior_v96j_preserved: %d\n', fixFlags.prior_v96j_preserved);
    fprintf(fid,'gasLP_valid_3obj: %d\n', fixFlags.gasLP_valid_3obj);
    fprintf(fid,'hybrid_valid_3obj: %d\n', fixFlags.hybrid_valid_3obj);
    fprintf(fid,'solar_penalized_3obj: %d\n', fixFlags.solar_penalized_3obj);
    fprintf(fid,'MR_consistency_pass: %d\n', fixFlags.MR_consistency_pass);
    fprintf(fid,'cost_consistency_pass: %d\n', fixFlags.cost_consistency_pass);
    fprintf(fid,'CO2_finite_positive_pass: %d\n', fixFlags.CO2_finite_positive_pass);
    fprintf(fid,'CO2_reduction_sanity_pass: %d\n', fixFlags.CO2_reduction_sanity_pass);
    fprintf(fid,'no_penalty_CO2_pass: %d\n', fixFlags.no_penalty_CO2_pass);
    fprintf(fid,'all_fix_checks_pass: %d\n', fixFlags.all_fix_checks_pass);
    fprintf(fid,'no_GA_executed: %d\n', fixFlags.no_GA_executed);
    fprintf(fid,'formal_run_still_on_hold: %d\n', fixFlags.formal_run_still_on_hold);
    fprintf(fid,'triobjective_smoke_pending: %d\n', fixFlags.triobjective_smoke_pending);
    fprintf(fid,'CO2_gas_specific: %.12g\n', CO2_gas);
    fprintf(fid,'CO2_hybrid_specific: %.12g\n', CO2_hyb);
    fprintf(fid,'CO2_reduction_pct: %.12g\n', CO2_reduction_pct);
    fprintf(fid,'outMd: %s\n', outMd);
    fprintf(fid,'outTxt: %s\n', outTxt);
    fprintf(fid,'outMat: %s\n', outMat);
    fclose(fid);

    fixout = struct();
    fixout.status = 'TRIOBJECTIVE_CO2_OBJECTIVE_FIX_COMPLETED';
    fixout.diagnosis = diagnosis;
    fixout.fixFlags = fixFlags;
    fixout.Teval = Teval;
    fixout.Tchecks = Tchecks;
    fixout.Tsource = Tsource;
    fixout.CO2_gas = CO2_gas;
    fixout.CO2_hyb = CO2_hyb;
    fixout.CO2_reduction_pct = CO2_reduction_pct;
    fixout.objective_v96j_fix1 = objective_v96j_fix1;
    fixout.outMd = outMd;
    fixout.outTxt = outTxt;
    fixout.outMat = outMat;

    disp('=== TRIOBJECTIVE_CO2_OBJECTIVE_FIX_v96j_b ===')
    disp(fixout.status)
    disp('=== DIAGNOSIS ===')
    disp(fixout.diagnosis)
    disp('=== FIX FLAGS ===')
    disp(fixout.fixFlags)
    disp('=== DIRECT EVALUATION ===')
    disp(fixout.Teval)
    disp('=== CHECKS ===')
    disp(fixout.Tchecks)
    disp('=== SOURCE SCAN ===')
    disp(fixout.Tsource)
    disp('=== KEY METRICS ===')
    fprintf('CO2_gas_specific = %.12g\n', fixout.CO2_gas);
    fprintf('CO2_hybrid_specific = %.12g\n', fixout.CO2_hyb);
    fprintf('CO2_reduction_pct = %.12g\n', fixout.CO2_reduction_pct);
    disp('=== OUTPUT FILES ===')
    disp(fixout.outMd)
    disp(fixout.outTxt)
    disp(fixout.outMat)

end

% =========================================================================
% Helpers del script de fix
% =========================================================================

function [f, detail, status, errMsg] = local_eval_v95j_fixscript(x, mode)
    status = "OK";
    errMsg = "";
    detail = struct();

    try
        [f, detail] = objective_productive_corrected_v95j_endpoint_TMAX_corrected(x, mode);
        f = double(f(:))';
    catch ME
        f = [1000, 1e6];
        detail = struct();
        status = "ERROR";
        errMsg = string(ME.message);
    end
end

function [f, detail, status, errMsg] = local_eval_v96j_fixscript(x, mode)
    status = "OK";
    errMsg = "";
    detail = struct();

    try
        [f, detail] = objective_productive_corrected_v96j_triobjective_CO2_fix1(x, mode);
        f = double(f(:))';

        if numel(f) ~= 3
            status = "BAD_OBJECTIVE_SIZE";
            f = [1000, 1e6, 1e6];
        end

        if any(~isfinite(f)) || any(~isreal(f))
            status = "BAD_OBJECTIVE_VALUE";
            f = [1000, 1e6, 1e6];
        end

    catch ME
        f = [1000, 1e6, 1e6];
        detail = struct();
        status = "ERROR";
        errMsg = string(ME.message);
    end
end

function row = local_eval_row_fixscript(mode, x, f95, d95, status95, err95, f96, d96, status96, err96)
    row = struct();

    row.mode = string(mode);

    row.m_max = x(1);
    row.T_min = x(2);
    row.r_div2 = x(3);
    row.t_rec_ini = x(4);

    row.v95_status = string(status95);
    row.v95_error = string(err95);
    row.v95_nobj = numel(f95);
    row.v95_f1 = local_vec_get_fixscript(f95,1,NaN);
    row.v95_f2 = local_vec_get_fixscript(f95,2,NaN);
    row.v95_detail_status = local_get_string_fixscript(d95, {'status','detail_status','execution_status'}, "UNKNOWN");

    row.v96_status = string(status96);
    row.v96_error = string(err96);
    row.v96_nobj = numel(f96);
    row.v96_f1 = local_vec_get_fixscript(f96,1,NaN);
    row.v96_f2 = local_vec_get_fixscript(f96,2,NaN);
    row.v96_f3 = local_vec_get_fixscript(f96,3,NaN);
    row.v96_detail_status = local_get_string_fixscript(d96, {'status','detail_status','execution_status'}, "UNKNOWN");

    row.v96_Q_aux_tot = local_get_numeric_fixscript(d96, {'outputs.Q_aux_tot','Q_aux_tot'}, NaN);
    row.v96_Irradiacion = local_get_numeric_fixscript(d96, {'outputs.Irradiacion','Irradiacion'}, NaN);
    row.v96_dry_time = local_get_numeric_fixscript(d96, {'outputs.dry_time','dry_time'}, NaN);
    row.v96_M = local_get_numeric_fixscript(d96, {'outputs.M','M'}, NaN);
    row.v96_MR = local_get_numeric_fixscript(d96, {'outputs.MR','MR'}, NaN);
    row.v96_Mf = local_get_numeric_fixscript(d96, {'product.Mf','Mf'}, NaN);
    row.v96_Mi = local_get_numeric_fixscript(d96, {'product.Mi','Mi'}, NaN);
    row.v96_M_des = local_get_numeric_fixscript(d96, {'product.M_des','M_des'}, NaN);

    row.v96_water_removed_kg = local_get_numeric_fixscript(d96, {'CO2.water_removed_kg'}, NaN);
    row.v96_E_electricity_kWh = local_get_numeric_fixscript(d96, {'CO2.E_electricity_kWh'}, NaN);
    row.v96_CO2_LPG_kg = local_get_numeric_fixscript(d96, {'CO2.CO2_LPG_kg'}, NaN);
    row.v96_CO2_electricity_kg = local_get_numeric_fixscript(d96, {'CO2.CO2_electricity_kg'}, NaN);
    row.v96_CO2_total_kg = local_get_numeric_fixscript(d96, {'CO2.CO2_total_kg'}, NaN);
    row.v96_CO2_specific = local_get_numeric_fixscript(d96, {'CO2.CO2_specific_kgCO2_per_kgwater','objectives.CO2_specific_kgCO2_per_kgwater'}, NaN);
    row.v96_emission_factor_status = local_get_string_fixscript(d96, {'CO2.emission_factor_status'}, "");
    row.v96_electricity_data_status = local_get_string_fixscript(d96, {'CO2.electricity_data_status'}, "");
end

function val = local_vec_get_fixscript(v, idx, defaultVal)
    if numel(v) >= idx
        val = v(idx);
    else
        val = defaultVal;
    end
end

function val = local_get_numeric_fixscript(S, paths, defaultVal)
    val = defaultVal;

    for k = 1:numel(paths)
        parts = split(string(paths{k}),'.');

        try
            tmp = S;
            ok = true;

            for j = 1:numel(parts)
                part = char(parts(j));
                if isstruct(tmp) && isfield(tmp, part)
                    tmp = tmp.(part);
                else
                    ok = false;
                    break
                end
            end

            if ok && isnumeric(tmp) && ~isempty(tmp)
                val = double(tmp(1));
                return
            end
        catch
        end
    end
end

function val = local_get_string_fixscript(S, paths, defaultVal)
    val = string(defaultVal);

    for k = 1:numel(paths)
        parts = split(string(paths{k}),'.');

        try
            tmp = S;
            ok = true;

            for j = 1:numel(parts)
                part = char(parts(j));
                if isstruct(tmp) && isfield(tmp, part)
                    tmp = tmp.(part);
                else
                    ok = false;
                    break
                end
            end

            if ok && ~isempty(tmp)
                val = string(tmp);
                return
            end
        catch
        end
    end
end

function row = local_source_row_fixscript(item, filePath, pattern, passVal, evidence)
    row = struct();
    row.item = string(item);
    row.file = string(filePath);
    row.pattern = string(pattern);
    row.pass = logical(passVal);
    row.evidence = string(evidence);
end

function row = local_source_contains_fixscript(item, filePath, pattern, evidenceIfFound)
    passVal = false;
    evidence = "FILE_NOT_FOUND";

    if isfile(filePath)
        try
            txt = fileread(filePath);
            passVal = contains(txt, pattern);
            if passVal
                evidence = string(evidenceIfFound);
            else
                evidence = "Pattern not found.";
            end
        catch ME
            evidence = "Could not read file: " + string(ME.message);
        end
    end

    row = local_source_row_fixscript(item, filePath, pattern, passVal, evidence);
end

function tf = local_source_pass_fixscript(Tsource, itemName)
    idx = strcmp(string(Tsource.item), string(itemName));
    if any(idx)
        tf = logical(Tsource.pass(find(idx,1,'first')));
    else
        tf = false;
    end
end

function row = local_check_row_fixscript(id, checkName, passVal, evidence, criterion)
    row = struct();
    row.id = string(id);
    row.check = string(checkName);
    row.pass = logical(passVal);
    row.evidence = string(evidence);
    row.criterion = string(criterion);
end