function impl = implement_nonphysical_penalty_wrapper_v628b()
% IMPLEMENT_NONPHYSICAL_PENALTY_WRAPPER_v628b
% Micropaso 6.28b — IMPLEMENT-NONPHYSICAL-PENALTY-WRAPPER-FIX-001
%
% Corrige el fallo de v628:
%   - No agrega funciones locales al final del wrapper.
%   - Crea una guarda externa:
%       wrappers/nonphysical_guard_eval_v628b.m
%   - Crea un wrapper controlado:
%       wrappers/opt_tunel_mod2_v17_nonphysical_penalty.m
%   - Crea una objective clonada desde v611:
%       production/objective_productive_corrected_v628b_nonphysical_penalty.m
%
% No modifica:
%   - v10
%   - v611
%   - corrida productiva original
%
% Uso:
%   impl = implement_nonphysical_penalty_wrapper_v628b();

    rootDir = setup_v05_paths();
    addpath(genpath(fullfile(rootDir,'02_src_limpio')));
    rehash;

    wrappersDir   = fullfile(rootDir,'02_src_limpio','wrappers');
    productionDir = fullfile(rootDir,'02_src_limpio','production');

    srcWrapper = fullfile(wrappersDir,'opt_tunel_mod2_v10_energy_mode_corrected.m');
    dstWrapper = fullfile(wrappersDir,'opt_tunel_mod2_v17_nonphysical_penalty.m');
    guardFile  = fullfile(wrappersDir,'nonphysical_guard_eval_v628b.m');

    if ~isfile(srcWrapper)
        error('No existe wrapper fuente: %s', srcWrapper);
    end

    % ---------------------------------------------------------------------
    % Localizar corrida productiva
    % ---------------------------------------------------------------------
    baseDir = fullfile(rootDir,'05_runs','productive_v614b');

    d = dir(baseDir);
    d = d([d.isdir]);
    d = d(~ismember({d.name},{'.','..','.MATLABDriveTag'}));

    keep = false(size(d));
    for ii = 1:numel(d)
        keep(ii) = startsWith(d(ii).name,'PRODUCTIVE_GA_CORRECTED_v614_');
    end
    d = d(keep);

    if isempty(d)
        error('No se encontró corrida PRODUCTIVE_GA_CORRECTED_v614_* en %s', baseDir);
    end

    [~,idxRun] = max([d.datenum]);
    runDir = fullfile(baseDir,d(idxRun).name);

    tablesDir = fullfile(runDir,'tables');
    matDir    = fullfile(runDir,'mat');
    logsDir   = fullfile(runDir,'logs');
    traceDir  = fullfile(runDir,'trace_v628b');

    if ~isfolder(traceDir), mkdir(traceDir); end
    if ~isfolder(tablesDir), mkdir(tablesDir); end
    if ~isfolder(matDir), mkdir(matDir); end
    if ~isfolder(logsDir), mkdir(logsDir); end

    selectedFile = fullfile(tablesDir,'SELECTED_SOLUTION_CORRECTED_v614b.csv');

    if ~isfile(selectedFile)
        error('No existe SELECTED_SOLUTION_CORRECTED_v614b.csv: %s', selectedFile);
    end

    Tsel = readtable(selectedFile);
    x = [Tsel.m_max(1), Tsel.T_min(1), Tsel.r_div2(1), Tsel.t_rec_ini(1)];

    % ---------------------------------------------------------------------
    % Parámetros reales confirmados desde objective_productive_corrected_v611
    % ---------------------------------------------------------------------
    W0    = 200;
    m_i   = 0.8700;
    m_f   = 0.0800;

    Mi    = 6.6923;
    Mf    = 0.0870;
    M_des = 0.1111;

    md    = 26.0000;
    mwi   = 174.0000;
    mwf   = 2.2609;

    % ---------------------------------------------------------------------
    % Crear guarda externa independiente
    % ---------------------------------------------------------------------
    guardText = sprintf([ ...
        'function [bad, diag] = nonphysical_guard_eval_v628b(i, Mf, ...\n' ...
        '    T_HE1_in, T_HE1_out, T_DH_in, T_DH_out, T_prod, T_amb, ...\n' ...
        '    HR_DH_in, HR_DH_out, HR_amb, ...\n' ...
        '    w_DH_in, w_DH_out, ...\n' ...
        '    M_prod, MR, Q_aux, I)\n' ...
        '%% NONPHYSICAL_GUARD_EVAL_v628b\n' ...
        '%% Guarda externa para evaluar dominio fisico en el indice i.\n' ...
        '\n' ...
        '    bad = false;\n' ...
        '    diag = struct();\n' ...
        '    diag.status = "OK";\n' ...
        '    diag.first_i = NaN;\n' ...
        '    diag.variable = "";\n' ...
        '    diag.rule = "";\n' ...
        '    diag.value_real = NaN;\n' ...
        '    diag.value_imag = NaN;\n' ...
        '    diag.priority = NaN;\n' ...
        '    diag.Mf = Mf;\n' ...
        '\n' ...
        '    violations = {};\n' ...
        '\n' ...
        '    violations = local_check(violations, i, "T_HE1_in",  T_HE1_in,  "temperature_low_high", -10, 120, 10);\n' ...
        '    violations = local_check(violations, i, "T_HE1_out", T_HE1_out, "temperature_low_high", -10, 120, 10);\n' ...
        '    violations = local_check(violations, i, "T_DH_in",   T_DH_in,   "temperature_low_high", -10, 120, 10);\n' ...
        '    violations = local_check(violations, i, "T_DH_out",  T_DH_out,  "temperature_low_high", -10, 120, 10);\n' ...
        '    violations = local_check(violations, i, "T_prod",    T_prod,    "temperature_low_high", -10, 120, 10);\n' ...
        '    violations = local_check(violations, i, "T_amb",     T_amb,     "temperature_low_high", -10, 120, 10);\n' ...
        '\n' ...
        '    violations = local_check(violations, i, "HR_DH_in",  HR_DH_in,  "relative_humidity_0_1", 0, 1, 20);\n' ...
        '    violations = local_check(violations, i, "HR_DH_out", HR_DH_out, "relative_humidity_0_1", 0, 1, 20);\n' ...
        '    violations = local_check(violations, i, "HR_amb",    HR_amb,    "relative_humidity_0_1", 0, 1, 20);\n' ...
        '\n' ...
        '    violations = local_check(violations, i, "w_DH_in",   w_DH_in,   "humidity_ratio_nonnegative", 0, Inf, 30);\n' ...
        '    violations = local_check(violations, i, "w_DH_out",  w_DH_out,  "humidity_ratio_nonnegative", 0, Inf, 30);\n' ...
        '\n' ...
        '    violations = local_check(violations, i, "M_prod",    M_prod,    "moisture_content_ge_Mf", Mf, Inf, 40);\n' ...
        '    violations = local_check(violations, i, "MR",        MR,        "MR_0_1", 0, 1, 50);\n' ...
        '    violations = local_check(violations, i, "Q_aux",     Q_aux,     "energy_aux_nonnegative", 0, Inf, 60);\n' ...
        '    violations = local_check(violations, i, "I",         I,         "irradiance_nonnegative", 0, Inf, 60);\n' ...
        '\n' ...
        '    if isempty(violations)\n' ...
        '        return\n' ...
        '    end\n' ...
        '\n' ...
        '    bad = true;\n' ...
        '    D = struct2table(vertcat(violations{:}));\n' ...
        '    D = sortrows(D,{''priority'',''variable''});\n' ...
        '\n' ...
        '    diag.status = "NONPHYSICAL_TRAJECTORY";\n' ...
        '    diag.first_i = i;\n' ...
        '    diag.variable = string(D.variable(1));\n' ...
        '    diag.rule = string(D.rule(1));\n' ...
        '    diag.value_real = D.value_real(1);\n' ...
        '    diag.value_imag = D.value_imag(1);\n' ...
        '    diag.priority = D.priority(1);\n' ...
        '    diag.all_violations = D;\n' ...
        'end\n' ...
        '\n' ...
        'function violations = local_check(violations, i, name, vec, rule, lower, upper, priority)\n' ...
        '    if isempty(vec)\n' ...
        '        return\n' ...
        '    end\n' ...
        '\n' ...
        '    idx = min(max(1,i),numel(vec));\n' ...
        '    val = double(vec(idx));\n' ...
        '    rv = real(val);\n' ...
        '    iv = imag(val);\n' ...
        '\n' ...
        '    bad_naninf = isnan(rv) || isinf(rv) || isnan(iv) || isinf(iv);\n' ...
        '    bad_complex = abs(iv) > 1e-9;\n' ...
        '\n' ...
        '    switch char(rule)\n' ...
        '        case ''temperature_low_high''\n' ...
        '            bad_rule = rv < lower || rv > upper;\n' ...
        '        case ''relative_humidity_0_1''\n' ...
        '            bad_rule = rv < lower || rv > upper;\n' ...
        '        case ''humidity_ratio_nonnegative''\n' ...
        '            bad_rule = rv < lower;\n' ...
        '        case ''moisture_content_ge_Mf''\n' ...
        '            bad_rule = rv < (lower - 1e-8);\n' ...
        '        case ''MR_0_1''\n' ...
        '            bad_rule = rv < lower || rv > upper;\n' ...
        '        case ''energy_aux_nonnegative''\n' ...
        '            bad_rule = rv < lower;\n' ...
        '        case ''irradiance_nonnegative''\n' ...
        '            bad_rule = rv < lower;\n' ...
        '        otherwise\n' ...
        '            bad_rule = false;\n' ...
        '    end\n' ...
        '\n' ...
        '    if ~(bad_naninf || bad_complex || bad_rule)\n' ...
        '        return\n' ...
        '    end\n' ...
        '\n' ...
        '    if bad_naninf\n' ...
        '        finalRule = string(rule) + "_nan_or_inf";\n' ...
        '        finalPriority = priority - 2;\n' ...
        '    elseif bad_complex\n' ...
        '        finalRule = string(rule) + "_complex";\n' ...
        '        finalPriority = priority - 1;\n' ...
        '    else\n' ...
        '        finalRule = string(rule);\n' ...
        '        finalPriority = priority;\n' ...
        '    end\n' ...
        '\n' ...
        '    one = struct();\n' ...
        '    one.variable = string(name);\n' ...
        '    one.rule = string(finalRule);\n' ...
        '    one.i = i;\n' ...
        '    one.value_real = rv;\n' ...
        '    one.value_imag = iv;\n' ...
        '    one.priority = finalPriority;\n' ...
        '\n' ...
        '    violations{end+1,1} = one;\n' ...
        'end\n' ...
    ]);

    fid = fopen(guardFile,'w');
    if fid < 0
        error('No se pudo crear guarda externa: %s', guardFile);
    end
    fwrite(fid,guardText);
    fclose(fid);

    % ---------------------------------------------------------------------
    % Crear wrapper v17 desde v10
    % ---------------------------------------------------------------------
    txt = fileread(srcWrapper);

    oldSignature = ...
        'function [Q_aux_tot, dry_time, M_prod_fin, MR_fin, Irradiacion, irr_diag] = opt_tunel_mod2_v10_energy_mode_corrected(m_max,T_min,r_div2,t_rec_ini, W0, m_i, Mi, mwi, md, m_f, Mf, mwf, M_des, mode_operation)';

    newSignature = ...
        'function [Q_aux_tot, dry_time, M_prod_fin, MR_fin, Irradiacion, irr_diag] = opt_tunel_mod2_v17_nonphysical_penalty(m_max,T_min,r_div2,t_rec_ini, W0, m_i, Mi, mwi, md, m_f, Mf, mwf, M_des, mode_operation)';

    if ~contains(txt, oldSignature)
        error('No se encontró la firma esperada de v10.');
    end

    txt = strrep(txt, oldSignature, newSignature);

    globalBlock = sprintf([ ...
        '\n' ...
        '    global TRACE_V628B_DIR TRACE_V628B_MODE TRACE_V628B_TAG\n' ...
        '\n' ...
    ]);

    txt = strrep(txt, newSignature, [newSignature, globalBlock]);

    oldDryBlockPattern = [
        '    if M_prod\(i\)<=M_des\s*' ...
        'Q_aux_tot=sum\(Q_aux\*t_step\*3600\)/1000;\s*' ...
        'Irradiacion=sum\(I\*t_step\*3600\*A_cap\*8\*mean\(ETHA_capt\)\)/1e6;\s*' ...
        'dry_time=t\(i\)/3600-t_ini;\s*' ...
        'M_prod_fin=M_prod\(i\);\s*' ...
        'MR_fin=MR\(i\);\s*' ...
        'break\s*' ...
        'end'
    ];

    guardBeforeDry = sprintf([ ...
        '    %% IMPLEMENT-NONPHYSICAL-PENALTY-WRAPPER-FIX-001\n' ...
        '    [nonphysical_v628b, guard_diag_v628b] = nonphysical_guard_eval_v628b( ...\n' ...
        '        i, Mf, ...\n' ...
        '        T_HE1_in, T_HE1_out, T_DH_in, T_DH_out, T_prod, T_amb, ...\n' ...
        '        HR_DH_in, HR_DH_out, HR_amb, ...\n' ...
        '        w_DH_in, w_DH_out, ...\n' ...
        '        M_prod, MR, Q_aux, I);\n' ...
        '\n' ...
        '    if nonphysical_v628b\n' ...
        '        Q_aux_tot = NaN;\n' ...
        '        Irradiacion = NaN;\n' ...
        '        dry_time = t(i)/3600-t_ini;\n' ...
        '        M_prod_fin = NaN;\n' ...
        '        MR_fin = 1000;\n' ...
        '\n' ...
        '        irr_diag.status = "NONPHYSICAL_TRAJECTORY";\n' ...
        '        irr_diag.termination_status = "NONPHYSICAL_TRAJECTORY";\n' ...
        '        irr_diag.nonphysical_guard = guard_diag_v628b;\n' ...
        '        irr_diag.mode_operation = string(mode_operation);\n' ...
        '\n' ...
        '        termination_status_v628b = "NONPHYSICAL_TRAJECTORY";\n' ...
        '        break_i_v628b = i;\n' ...
        '        guard_diag_saved_v628b = guard_diag_v628b;\n' ...
        '\n' ...
        '        if ~isempty(TRACE_V628B_DIR)\n' ...
        '            if ~isfolder(TRACE_V628B_DIR), mkdir(TRACE_V628B_DIR); end\n' ...
        '            safeMode_v628b = char(string(TRACE_V628B_MODE));\n' ...
        '            safeMode_v628b = regexprep(safeMode_v628b,''[^a-zA-Z0-9_]'',''_'');\n' ...
        '            safeTag_v628b = char(string(TRACE_V628B_TAG));\n' ...
        '            safeTag_v628b = regexprep(safeTag_v628b,''[^a-zA-Z0-9_]'',''_'');\n' ...
        '            trace_file_v628b = fullfile(TRACE_V628B_DIR, sprintf(''TRACE_v628b_%%s_%%s_nonphysical.mat'', safeMode_v628b, safeTag_v628b));\n' ...
        '            save(trace_file_v628b);\n' ...
        '        end\n' ...
        '\n' ...
        '        break\n' ...
        '    end\n\n' ...
    ]);

    [s1,e1] = regexp(txt, oldDryBlockPattern, 'start', 'end');

    if numel(s1) ~= 1
        error('No se encontró exactamente una vez el bloque M_prod<=M_des. Coincidencias: %d', numel(s1));
    end

    oldDryBlockText = txt(s1:e1);
    txt = [txt(1:s1-1), guardBeforeDry, oldDryBlockText, txt(e1+1:end)];

    % Reemplazar salida normal M_des
    newDryBlock = sprintf([ ...
        '    if M_prod(i)<=M_des\n' ...
        '        Q_aux_tot=sum(Q_aux*t_step*3600)/1000;\n' ...
        '        Irradiacion=sum(I*t_step*3600*A_cap*8*mean(ETHA_capt))/1e6;\n' ...
        '        dry_time=t(i)/3600-t_ini;\n' ...
        '        M_prod_fin=M_prod(i);\n' ...
        '        MR_fin=MR(i);\n' ...
        '\n' ...
        '        irr_diag.status = "OK";\n' ...
        '        irr_diag.termination_status = "M_DES_REACHED";\n' ...
        '        irr_diag.mode_operation = string(mode_operation);\n' ...
        '\n' ...
        '        termination_status_v628b = "M_DES_REACHED";\n' ...
        '        break_i_v628b = i;\n' ...
        '\n' ...
        '        if ~isempty(TRACE_V628B_DIR)\n' ...
        '            if ~isfolder(TRACE_V628B_DIR), mkdir(TRACE_V628B_DIR); end\n' ...
        '            safeMode_v628b = char(string(TRACE_V628B_MODE));\n' ...
        '            safeMode_v628b = regexprep(safeMode_v628b,''[^a-zA-Z0-9_]'',''_'');\n' ...
        '            safeTag_v628b = char(string(TRACE_V628B_TAG));\n' ...
        '            safeTag_v628b = regexprep(safeTag_v628b,''[^a-zA-Z0-9_]'',''_'');\n' ...
        '            trace_file_v628b = fullfile(TRACE_V628B_DIR, sprintf(''TRACE_v628b_%%s_%%s_normal.mat'', safeMode_v628b, safeTag_v628b));\n' ...
        '            save(trace_file_v628b);\n' ...
        '        end\n' ...
        '\n' ...
        '        break\n' ...
        '    end' ...
    ]);

    [s2,e2] = regexp(txt, oldDryBlockPattern, 'start', 'end');

    if numel(s2) ~= 1
        error('No se encontró exactamente una vez el bloque M_prod<=M_des después de insertar guarda. Coincidencias: %d', numel(s2));
    end

    txt = [txt(1:s2-1), newDryBlock, txt(e2+1:end)];

    % Reemplazar salida tmax
    oldTmaxBlockPattern = [
        '    if t\(i\)>=\(t_max-t_step\)\*3600\s*' ...
        'Q_aux_tot=sum\(Q_aux\*t_step\*3600\)/1000;\s*' ...
        'Irradiacion=sum\(I\*t_step\*3600\*A_cap\*8\*mean\(ETHA_capt\)\)/1e6;\s*' ...
        'dry_time=t\(i\)/3600-t_ini;\s*' ...
        'M_prod_fin=min\(M_prod\);\s*' ...
        'MR_fin=MR\(end-1\);\s*' ...
        'break\s*' ...
        'end'
    ];

    newTmaxBlock = sprintf([ ...
        '    if t(i)>=(t_max-t_step)*3600\n' ...
        '        Q_aux_tot=sum(Q_aux*t_step*3600)/1000;\n' ...
        '        Irradiacion=sum(I*t_step*3600*A_cap*8*mean(ETHA_capt))/1e6;\n' ...
        '        dry_time=t(i)/3600-t_ini;\n' ...
        '        M_prod_fin=min(M_prod);\n' ...
        '        MR_fin=MR(end-1);\n' ...
        '\n' ...
        '        irr_diag.status = "OK";\n' ...
        '        irr_diag.termination_status = "TMAX_REACHED";\n' ...
        '        irr_diag.mode_operation = string(mode_operation);\n' ...
        '\n' ...
        '        termination_status_v628b = "TMAX_REACHED";\n' ...
        '        break_i_v628b = i;\n' ...
        '\n' ...
        '        if ~isempty(TRACE_V628B_DIR)\n' ...
        '            if ~isfolder(TRACE_V628B_DIR), mkdir(TRACE_V628B_DIR); end\n' ...
        '            safeMode_v628b = char(string(TRACE_V628B_MODE));\n' ...
        '            safeMode_v628b = regexprep(safeMode_v628b,''[^a-zA-Z0-9_]'',''_'');\n' ...
        '            safeTag_v628b = char(string(TRACE_V628B_TAG));\n' ...
        '            safeTag_v628b = regexprep(safeTag_v628b,''[^a-zA-Z0-9_]'',''_'');\n' ...
        '            trace_file_v628b = fullfile(TRACE_V628B_DIR, sprintf(''TRACE_v628b_%%s_%%s_tmax.mat'', safeMode_v628b, safeTag_v628b));\n' ...
        '            save(trace_file_v628b);\n' ...
        '        end\n' ...
        '\n' ...
        '        break\n' ...
        '    end' ...
    ]);

    [s3,e3] = regexp(txt, oldTmaxBlockPattern, 'start', 'end');

    if numel(s3) ~= 1
        error('No se encontró exactamente una vez el bloque t_max. Coincidencias: %d', numel(s3));
    end

    txt = [txt(1:s3-1), newTmaxBlock, txt(e3+1:end)];

    fid = fopen(dstWrapper,'w');
    if fid < 0
        error('No se pudo crear wrapper v17: %s', dstWrapper);
    end
    fwrite(fid,txt);
    fclose(fid);

    clear nonphysical_guard_eval_v628b
    clear opt_tunel_mod2_v17_nonphysical_penalty
    rehash;

    if isempty(which('nonphysical_guard_eval_v628b'))
        error('Se creó nonphysical_guard_eval_v628b, pero MATLAB no la encuentra en path.');
    end

    if isempty(which('opt_tunel_mod2_v17_nonphysical_penalty'))
        error('Se creó v17, pero MATLAB no lo encuentra en path.');
    end

    % ---------------------------------------------------------------------
    % Crear objective v628b clonada desde v611
    % ---------------------------------------------------------------------
    obj611 = which('objective_productive_corrected_v611');

    if isempty(obj611)
        error('No se encontró objective_productive_corrected_v611.');
    end

    obj628b = fullfile(productionDir,'objective_productive_corrected_v628b_nonphysical_penalty.m');

    objTxt = fileread(obj611);

    objTxt = strrep(objTxt, ...
        'objective_productive_corrected_v611', ...
        'objective_productive_corrected_v628b_nonphysical_penalty');

    objTxt = strrep(objTxt, ...
        'opt_tunel_mod2_v10_energy_mode_corrected', ...
        'opt_tunel_mod2_v17_nonphysical_penalty');

    fid = fopen(obj628b,'w');
    if fid < 0
        error('No se pudo crear objective v628b: %s', obj628b);
    end
    fwrite(fid,objTxt);
    fclose(fid);

    clear objective_productive_corrected_v628b_nonphysical_penalty
    rehash;

    if isempty(which('objective_productive_corrected_v628b_nonphysical_penalty'))
        error('Se creó objective v628b, pero MATLAB no la encuentra en path.');
    end

    % ---------------------------------------------------------------------
    % Evaluación directa wrapper v17 y objective v628b
    % ---------------------------------------------------------------------
    global TRACE_V628B_DIR TRACE_V628B_MODE TRACE_V628B_TAG

    modes = ["gasLP","hybrid","solar"];

    directRows = {};
    objRows = {};

    for k = 1:numel(modes)
        mode = modes(k);

        TRACE_V628B_DIR = traceDir;
        TRACE_V628B_MODE = mode;
        TRACE_V628B_TAG = "selected_solution";

        filesToDelete = dir(fullfile(traceDir, sprintf('TRACE_v628b_%s_selected_solution_*.mat', char(mode))));
        for ff = 1:numel(filesToDelete)
            delete(fullfile(traceDir, filesToDelete(ff).name));
        end

        row = struct();
        row.mode = mode;

        try
            [Q_aux_tot, dry_time, M, MR, Irradiacion, irr_diag] = ...
                opt_tunel_mod2_v17_nonphysical_penalty( ...
                    x(1), x(2), x(3), x(4), ...
                    W0, m_i, Mi, mwi, md, m_f, Mf, mwf, M_des, mode);

            row.status = "OK";
            row.error_message = "";
            row.Q_aux_tot = Q_aux_tot;
            row.Irradiacion = Irradiacion;
            row.dry_time = dry_time;
            row.M = M;
            row.MR = MR;

            if exist('irr_diag','var') && isstruct(irr_diag) && isfield(irr_diag,'status')
                row.irr_status = string(irr_diag.status);
            else
                row.irr_status = "UNKNOWN";
            end

            if exist('irr_diag','var') && isstruct(irr_diag) && isfield(irr_diag,'termination_status')
                row.termination_status = string(irr_diag.termination_status);
            else
                row.termination_status = "UNKNOWN";
            end

            if exist('irr_diag','var') && isstruct(irr_diag) && isfield(irr_diag,'nonphysical_guard')
                gd = irr_diag.nonphysical_guard;
                row.guard_variable = string(gd.variable);
                row.guard_rule = string(gd.rule);
                row.guard_i = gd.first_i;
                row.guard_value_real = gd.value_real;
                row.guard_value_imag = gd.value_imag;
            else
                row.guard_variable = "";
                row.guard_rule = "";
                row.guard_i = NaN;
                row.guard_value_real = NaN;
                row.guard_value_imag = NaN;
            end

        catch ME
            row.status = "ERROR";
            row.error_message = string(ME.message);
            row.Q_aux_tot = NaN;
            row.Irradiacion = NaN;
            row.dry_time = NaN;
            row.M = NaN;
            row.MR = NaN;
            row.irr_status = "ERROR";
            row.termination_status = "ERROR";
            row.guard_variable = "";
            row.guard_rule = "";
            row.guard_i = NaN;
            row.guard_value_real = NaN;
            row.guard_value_imag = NaN;
        end

        nonphysFile = fullfile(traceDir, sprintf('TRACE_v628b_%s_selected_solution_nonphysical.mat', char(mode)));
        normalFile  = fullfile(traceDir, sprintf('TRACE_v628b_%s_selected_solution_normal.mat', char(mode)));
        tmaxFile    = fullfile(traceDir, sprintf('TRACE_v628b_%s_selected_solution_tmax.mat', char(mode)));

        row.trace_nonphysical_exists = isfile(nonphysFile);
        row.trace_normal_exists = isfile(normalFile);
        row.trace_tmax_exists = isfile(tmaxFile);
        row.trace_nonphysical_file = string(nonphysFile);
        row.trace_normal_file = string(normalFile);
        row.trace_tmax_file = string(tmaxFile);

        directRows{end+1,1} = row; %#ok<AGROW>

        orow = struct();
        orow.mode = mode;

        try
            [f628b,d628b] = objective_productive_corrected_v628b_nonphysical_penalty(x, mode);

            orow.status = "OK";
            orow.error_message = "";
            orow.MR_objective = f628b(1);
            orow.cost_objective = f628b(2);

            if isfield(d628b,'status')
                orow.detail_status = string(d628b.status);
            else
                orow.detail_status = "UNKNOWN";
            end

            if isfield(d628b,'outputs') && isfield(d628b.outputs,'M')
                orow.M = d628b.outputs.M;
            else
                orow.M = NaN;
            end

            if isfield(d628b,'outputs') && isfield(d628b.outputs,'MR')
                orow.MR = d628b.outputs.MR;
            else
                orow.MR = NaN;
            end

            if isfield(d628b,'outputs') && isfield(d628b.outputs,'Q_aux_tot')
                orow.Q_aux_tot = d628b.outputs.Q_aux_tot;
            else
                orow.Q_aux_tot = NaN;
            end

            if isfield(d628b,'outputs') && isfield(d628b.outputs,'Irradiacion')
                orow.Irradiacion = d628b.outputs.Irradiacion;
            else
                orow.Irradiacion = NaN;
            end

        catch ME
            orow.status = "ERROR";
            orow.error_message = string(ME.message);
            orow.MR_objective = NaN;
            orow.cost_objective = NaN;
            orow.detail_status = "ERROR";
            orow.M = NaN;
            orow.MR = NaN;
            orow.Q_aux_tot = NaN;
            orow.Irradiacion = NaN;
        end

        objRows{end+1,1} = orow; %#ok<AGROW>
    end

    Tdirect = struct2table(vertcat(directRows{:}));
    Tobj = struct2table(vertcat(objRows{:}));

    % ---------------------------------------------------------------------
    % Diagnóstico
    % ---------------------------------------------------------------------
    flags = struct();

    gasRowD = strcmp(Tdirect.mode,"gasLP");
    hybRowD = strcmp(Tdirect.mode,"hybrid");
    solRowD = strcmp(Tdirect.mode,"solar");

    gasRowO = strcmp(Tobj.mode,"gasLP");
    hybRowO = strcmp(Tobj.mode,"hybrid");
    solRowO = strcmp(Tobj.mode,"solar");

    flags.direct_all_status_ok = all(strcmp(Tdirect.status,"OK"));
    flags.objective_all_status_ok = all(strcmp(Tobj.status,"OK"));

    flags.gas_direct_ok = strcmp(Tdirect.irr_status(gasRowD),"OK");
    flags.hybrid_direct_ok = strcmp(Tdirect.irr_status(hybRowD),"OK");
    flags.solar_direct_nonphysical = strcmp(Tdirect.irr_status(solRowD),"NONPHYSICAL_TRAJECTORY");

    flags.solar_trace_nonphysical_exists = Tdirect.trace_nonphysical_exists(solRowD);

    flags.solar_objective_penalized = ...
        Tobj.MR_objective(solRowO) >= 1000 || Tobj.cost_objective(solRowO) >= 1e6;

    flags.gas_objective_not_penalized = ...
        Tobj.MR_objective(gasRowO) < 1000 && Tobj.cost_objective(gasRowO) < 1e6;

    flags.hybrid_objective_not_penalized = ...
        Tobj.MR_objective(hybRowO) < 1000 && Tobj.cost_objective(hybRowO) < 1e6;

    if ~flags.direct_all_status_ok
        diagnosis = "IMPLEMENTATION_DIRECT_WRAPPER_ERROR";
    elseif ~flags.objective_all_status_ok
        diagnosis = "IMPLEMENTATION_OBJECTIVE_ERROR";
    elseif flags.solar_direct_nonphysical && flags.gas_direct_ok && flags.hybrid_direct_ok && ...
            flags.solar_objective_penalized && flags.gas_objective_not_penalized && flags.hybrid_objective_not_penalized
        diagnosis = "NONPHYSICAL_PENALTY_IMPLEMENTATION_PASS";
    elseif flags.solar_direct_nonphysical && flags.gas_direct_ok && flags.hybrid_direct_ok
        diagnosis = "WRAPPER_PENALTY_PASS_OBJECTIVE_POLICY_REVIEW";
    else
        diagnosis = "NONPHYSICAL_PENALTY_IMPLEMENTATION_REQUIRES_REVIEW";
    end

    % ---------------------------------------------------------------------
    % Guardar salidas
    % ---------------------------------------------------------------------
    outCsvDirect = fullfile(tablesDir,'IMPLEMENT_NONPHYSICAL_PENALTY_WRAPPER_v628b_direct.csv');
    outCsvObj    = fullfile(tablesDir,'IMPLEMENT_NONPHYSICAL_PENALTY_WRAPPER_v628b_objective.csv');
    outMat       = fullfile(matDir,'IMPLEMENT_NONPHYSICAL_PENALTY_WRAPPER_v628b.mat');
    outLog       = fullfile(logsDir,'IMPLEMENT_NONPHYSICAL_PENALTY_WRAPPER_v628b.txt');

    writetable(Tdirect,outCsvDirect);
    writetable(Tobj,outCsvObj);

    save(outMat,'Tdirect','Tobj','flags','diagnosis','x','runDir','traceDir','dstWrapper','guardFile','obj628b');

    fid = fopen(outLog,'w');
    fprintf(fid,'IMPLEMENT-NONPHYSICAL-PENALTY-WRAPPER-FIX-001\n');
    fprintf(fid,'status: IMPLEMENT_NONPHYSICAL_PENALTY_WRAPPER_FIX_COMPLETED\n');
    fprintf(fid,'diagnosis: %s\n', diagnosis);
    fprintf(fid,'runDir: %s\n', runDir);
    fprintf(fid,'traceDir: %s\n', traceDir);
    fprintf(fid,'guardFile: %s\n', guardFile);
    fprintf(fid,'dstWrapper: %s\n', dstWrapper);
    fprintf(fid,'obj628b: %s\n', obj628b);
    fprintf(fid,'outCsvDirect: %s\n', outCsvDirect);
    fprintf(fid,'outCsvObj: %s\n', outCsvObj);
    fprintf(fid,'outMat: %s\n', outMat);
    fprintf(fid,'timestamp: %s\n\n', datestr(now,'yyyy-mm-dd HH:MM:SS'));

    fprintf(fid,'--- DIRECT WRAPPER TABLE ---\n');
    for r = 1:height(Tdirect)
        fprintf(fid,'mode: %s\n', Tdirect.mode(r));
        fprintf(fid,'status: %s\n', Tdirect.status(r));
        fprintf(fid,'irr_status: %s\n', Tdirect.irr_status(r));
        fprintf(fid,'termination_status: %s\n', Tdirect.termination_status(r));
        fprintf(fid,'Q_aux_tot: %.12g\n', Tdirect.Q_aux_tot(r));
        fprintf(fid,'Irradiacion: %.12g\n', Tdirect.Irradiacion(r));
        fprintf(fid,'dry_time: %.12g\n', Tdirect.dry_time(r));
        fprintf(fid,'M: %.12g\n', Tdirect.M(r));
        fprintf(fid,'MR: %.12g\n', Tdirect.MR(r));
        fprintf(fid,'guard_variable: %s\n', Tdirect.guard_variable(r));
        fprintf(fid,'guard_rule: %s\n', Tdirect.guard_rule(r));
        fprintf(fid,'guard_i: %.0f\n', Tdirect.guard_i(r));
        fprintf(fid,'guard_value_real: %.12g\n\n', Tdirect.guard_value_real(r));
    end

    fprintf(fid,'--- OBJECTIVE TABLE ---\n');
    for r = 1:height(Tobj)
        fprintf(fid,'mode: %s\n', Tobj.mode(r));
        fprintf(fid,'status: %s\n', Tobj.status(r));
        fprintf(fid,'MR_objective: %.12g\n', Tobj.MR_objective(r));
        fprintf(fid,'cost_objective: %.12g\n', Tobj.cost_objective(r));
        fprintf(fid,'detail_status: %s\n', Tobj.detail_status(r));
        fprintf(fid,'Q_aux_tot: %.12g\n', Tobj.Q_aux_tot(r));
        fprintf(fid,'Irradiacion: %.12g\n', Tobj.Irradiacion(r));
        fprintf(fid,'M: %.12g\n', Tobj.M(r));
        fprintf(fid,'MR: %.12g\n\n', Tobj.MR(r));
    end

    fclose(fid);

    impl = struct();
    impl.status = 'IMPLEMENT_NONPHYSICAL_PENALTY_WRAPPER_FIX_COMPLETED';
    impl.diagnosis = diagnosis;
    impl.flags = flags;
    impl.Tdirect = Tdirect;
    impl.Tobj = Tobj;
    impl.runDir = runDir;
    impl.traceDir = traceDir;
    impl.guardFile = guardFile;
    impl.dstWrapper = dstWrapper;
    impl.obj628b = obj628b;
    impl.outCsvDirect = outCsvDirect;
    impl.outCsvObj = outCsvObj;
    impl.outMat = outMat;
    impl.outLog = outLog;

    disp('=== IMPLEMENT_NONPHYSICAL_PENALTY_WRAPPER_v628b ===')
    disp(impl.status)
    disp('=== DIAGNOSIS ===')
    disp(impl.diagnosis)
    disp('=== FLAGS ===')
    disp(impl.flags)
    disp('=== DIRECT WRAPPER TABLE ===')
    disp(Tdirect)
    disp('=== OBJECTIVE TABLE ===')
    disp(Tobj)
    disp('=== OUTPUT FILES ===')
    disp(impl.outCsvDirect)
    disp(impl.outCsvObj)
    disp(impl.outMat)
    disp(impl.outLog)
end