% v95j endpoint-TMAX-corrected objective clone generated by implement_tmax_endpoint_correction_clone_v95j on 2026-06-27 11:23:01
% Calls opt_tunel_mod2_v18_endpoint_TMAX_corrected.
function [f, detail] = objective_productive_corrected_v96j_triobjective_CO2(x, mode_operation)
%OBJECTIVE_PRODUCTIVE_CORRECTED_V611 Corrected productive objective.
%
% Micropaso 6.11 — OBJECTIVE-PRODUCTIVE-CORRECTED-001
%
% Objectives returned to gamultiobj:
%   f(1) = MR_final
%   f(2) = cost_specific_USD_per_kgwater
%
% Scope:
%   - Uses corrected wrapper:
%     opt_tunel_mod2_v18_endpoint_TMAX_corrected.m
%   - Uses audited historical cost functions:
%     build_cost_params_historical.m
%     calc_cost_breakdown.m
%
% This function does not run GA by itself.
% This function does not write article figures.
% This function does not declare final article results.
%
% Emissions objective:
%   Not included in v6.11 because emission factors have not been audited
%   in the current controlled branch.

    if nargin < 2 || isempty(mode_operation)
        mode_operation = 'hybrid';
    end

    rootDir = setup_v05_paths();
    addpath(genpath(fullfile(rootDir,'02_src_limpio')));
    rehash;

    %% Default penalty values for gamultiobj robustness
    penalty_MR = 1e3;
    penalty_cost = 1e6;

    f = [penalty_MR, penalty_cost, penalty_CO2];

    detail = struct();
    detail.created_at = datetime('now');
    detail.endpoint_TMAX_correction = "v95j_v18_current_state_recalculated_MR";
    detail.created_by_function = 'objective_productive_corrected_v96j_triobjective_CO2';
    detail.status = 'NOT_EVALUATED';
    detail.mode_operation = mode_operation;
    detail.note = 'Corrected objective for productive GA; no GA execution inside this function.';

    try
        %% Validate decision vector
        if ~isnumeric(x)
            error('Decision vector x must be numeric.');
        end

        x = double(x(:)');

        if numel(x) ~= 4
            error('Decision vector x must have four elements: [m_max T_min r_div2 t_rec_ini].');
        end

        m_max = x(1);
        T_min = x(2);
        r_div2 = x(3);
        t_rec_ini = x(4);

        lb = [0.07 45 0.00 0];
        ub = [0.20 70 0.99 19];

        if any(x < lb) || any(x > ub)
            detail.status = 'OUT_OF_BOUNDS';
            detail.x = x;
            detail.lb = lb;
            detail.ub = ub;
            return
        end

        %% Product parameters — red chili productive baseline
        W0 = 200;

        m_i = 0.87;
        Mi = m_i/(1-m_i);
        mwi = W0*m_i;
        md = mwi/Mi;

        m_f = 0.08;
        m_des = 0.10;
        Mf = m_f/(1-m_f);
        M_des = m_des/(1-m_des);
        mwf = Mf*md;

        %% Corrected model call
        [Q_aux_tot, dry_time, M, MR, Irradiacion, irr_diag] = ...
            opt_tunel_mod2_v18_endpoint_TMAX_corrected( ...
                m_max, T_min, r_div2, t_rec_ini, ...
                W0, m_i, Mi, mwi, md, m_f, Mf, mwf, M_des, mode_operation);

        %% Audited historical cost
        params_cost = build_cost_params_historical();

        cost = calc_cost_breakdown( ...
            dry_time, Q_aux_tot, Irradiacion, Mi, M, md, params_cost);

        cost_specific = cost.cost_specific_USD_per_kgwater;

        %% Finite objective protection
        if isnan(MR) || isinf(MR)
            detail.status = 'INVALID_MR';
            return
        end

        if isnan(cost_specific) || isinf(cost_specific) || cost_specific <= 0
            detail.status = 'INVALID_COST';
            return
        end

        %% Final objective vector
        f = [MR, cost_specific];

        detail.status = 'OK';
        detail.x = x;

        detail.inputs.m_max = m_max;
        detail.inputs.T_min = T_min;
        detail.inputs.r_div2 = r_div2;
        detail.inputs.t_rec_ini = t_rec_ini;

        detail.product.W0 = W0;
        detail.product.m_i = m_i;
        detail.product.m_f = m_f;
        detail.product.m_des = m_des;
        detail.product.Mi = Mi;
        detail.product.Mf = Mf;
        detail.product.M_des = M_des;
        detail.product.md = md;
        detail.product.mwi = mwi;
        detail.product.mwf = mwf;

        detail.outputs.Q_aux_tot = Q_aux_tot;
        detail.outputs.dry_time = dry_time;
        detail.outputs.M = M;
        detail.outputs.MR = MR;
        detail.outputs.Irradiacion = Irradiacion;

        detail.irradiance.rule = irr_diag.rule;

        if isfield(irr_diag,'aux_rule')
            detail.auxiliary.rule = irr_diag.aux_rule;
        else
            detail.auxiliary.rule = 'aux_rule_not_reported';
        end

        detail.cost = cost;
        
    % --- v96j triobjective CO2 block ---------------------------------
    % Provisional emission factors for computational validation only.
    % Must be replaced/confirmed before manuscript use.
    EF_LPG_kgCO2_per_kWh = 0.2270;
    EF_grid_kgCO2_per_kWh = 0.4380;
    emission_factor_status = "PROVISIONAL_FOR_CODE_VALIDATION";
    
    water_removed_kg = NaN;
    if isfield(detail, "product") && isfield(detail.product, "mwi") && isfield(detail.product, "mwf")
        water_removed_kg = detail.product.mwi - detail.product.mwf;
    elseif isfield(detail, "product") && isfield(detail.product, "water_removed_kg")
        water_removed_kg = detail.product.water_removed_kg;
    end
    
    E_electricity_kWh = NaN;
    if isfield(detail, "cost") && isfield(detail.cost, "electricity_kWh")
        E_electricity_kWh = detail.cost.electricity_kWh;
    elseif isfield(detail, "cost") && isfield(detail.cost, "electric_energy_kWh")
        E_electricity_kWh = detail.cost.electric_energy_kWh;
    elseif isfield(detail, "cost") && isfield(detail.cost, "electricity_cost_USD")
        % Fallback conservative reconstruction only if electricity cost exists.
        % The divisor is intentionally NaN unless a tariff is stored.
        E_electricity_kWh = NaN;
    end
    
    if isnan(E_electricity_kWh)
        % Current audited cost route does not expose electricity kWh separately.
        % The electricity contribution is set to zero for computational validation,
        % and flagged as provisional. This must be corrected if electricity data are later exposed.
        E_electricity_kWh = 0;
        electricity_data_status = "NOT_EXPOSED_ASSUMED_ZERO_FOR_VALIDATION";
    else
        electricity_data_status = "EXTRACTED_FROM_DETAIL";
    end
    
    CO2_LPG_kg = Q_aux_tot * EF_LPG_kgCO2_per_kWh;
    CO2_electricity_kg = E_electricity_kWh * EF_grid_kgCO2_per_kWh;
    CO2_total_kg = CO2_LPG_kg + CO2_electricity_kg;
    CO2_specific_kgCO2_per_kgwater = CO2_total_kg / water_removed_kg;
    
    if ~isfinite(CO2_specific_kgCO2_per_kgwater) || ~isreal(CO2_specific_kgCO2_per_kgwater) || CO2_specific_kgCO2_per_kgwater < 0
        f = [1000, 1e6, 1e6];
        detail.status = "INVALID_CO2";
    else
        f = [f(1), f(2), CO2_specific_kgCO2_per_kgwater];
    end
    
    detail.CO2 = struct();
    detail.CO2.EF_LPG_kgCO2_per_kWh = EF_LPG_kgCO2_per_kWh;
    detail.CO2.EF_grid_kgCO2_per_kWh = EF_grid_kgCO2_per_kWh;
    detail.CO2.emission_factor_status = emission_factor_status;
    detail.CO2.electricity_data_status = electricity_data_status;
    detail.CO2.water_removed_kg = water_removed_kg;
    detail.CO2.E_electricity_kWh = E_electricity_kWh;
    detail.CO2.CO2_LPG_kg = CO2_LPG_kg;
    detail.CO2.CO2_electricity_kg = CO2_electricity_kg;
    detail.CO2.CO2_total_kg = CO2_total_kg;
    detail.CO2.CO2_specific_kgCO2_per_kgwater = CO2_specific_kgCO2_per_kgwater;
    detail.CO2.scope = "TRIOBJECTIVE_COMPUTATIONAL_VALIDATION_FACTORS_PROVISIONAL";
    % ----------------------------------------------------------------

detail.objectives.MR_final = f(1);
        detail.objectives.cost_specific_USD_per_kgwater = f(2);
    detail.objectives.CO2_specific_kgCO2_per_kgwater = f(3);

        detail.execution.GA_executed = false;
        detail.execution.article_figures_declared = false;

    catch ME
        detail.status = 'ERROR_CAUGHT_RETURNING_PENALTY';
        detail.error.identifier = ME.identifier;
        detail.error.message = ME.message;
        detail.error.stack = ME.stack;
        f = [penalty_MR, penalty_cost, penalty_CO2];
    end
end