file = fullfile(rootDir,'02_src_limpio','production','productive_run_control_v68.m');

code = [
"function control = productive_run_control_v68()" newline ...
"%PRODUCTIVE_RUN_CONTROL_V68 Pre-run control before productive GA/batch runs." newline ...
"%" newline ...
"% Micropaso 6.8 — PRODUCTIVE-RUN-CONTROL-001" newline ...
"%" newline ...
"% Does not run GA." newline ...
"% Does not run long sweeps." newline ...
"% Does not modify costs." newline ...
"% Does not declare final article results." newline ...
"" newline ...
"    rootDir = setup_v05_paths();" newline ...
"" newline ...
"    %% PROD-RUN-PATH-B-001: ensure required source folders are visible" newline ...
"    addpath(fullfile(rootDir,'02_src_limpio','production'));" newline ...
"    addpath(fullfile(rootDir,'02_src_limpio','comparison'));" newline ...
"    addpath(fullfile(rootDir,'02_src_limpio','validation'));" newline ...
"    addpath(fullfile(rootDir,'02_src_limpio','wrappers'));" newline ...
"    addpath(fullfile(rootDir,'02_src_limpio','cost'));" newline ...
"    rehash;" newline ...
"" newline ...
"    logDir  = fullfile(rootDir,'06_outputs','logs');" newline ...
"    tabDir  = fullfile(rootDir,'06_outputs','tables');" newline ...
"    compDir = fullfile(rootDir,'06_outputs','comparisons');" newline ...
"" newline ...
"    if ~exist(logDir,'dir'), mkdir(logDir); end" newline ...
"    if ~exist(tabDir,'dir'), mkdir(tabDir); end" newline ...
"    if ~exist(compDir,'dir'), mkdir(compDir); end" newline ...
"" newline ...
"    required_files = {" newline ...
"        fullfile(rootDir,'02_src_limpio','wrappers','opt_tunel_mod2_v10_energy_mode_corrected.m')" newline ...
"        fullfile(rootDir,'02_src_limpio','wrappers','opt_tunel_mod2_v06_data_controlled.m')" newline ...
"        fullfile(rootDir,'02_src_limpio','comparison','compare_operation_modes.m')" newline ...
"        fullfile(rootDir,'02_src_limpio','validation','test_hybrid_irradiance_modes_v10.m')" newline ...
"        fullfile(rootDir,'02_src_limpio','validation','test_hybrid_irradiance_modes_v10_robustness.m')" newline ...
"        fullfile(rootDir,'02_src_limpio','cost','calc_cost_breakdown.m')" newline ...
"        fullfile(rootDir,'02_src_limpio','cost','build_cost_params_historical.m')" newline ...
"    };" newline ...
"" newline ...
"    required_labels = {" newline ...
"        'corrected_energy_mode_wrapper'" newline ...
"        'historical_wrapper_preserved'" newline ...
"        'compare_operation_modes'" newline ...
"        'hybrid_irradiance_mode_test'" newline ...
"        'hybrid_irradiance_robustness_test'" newline ...
"        'cost_breakdown'" newline ...
"        'historical_cost_params'" newline ...
"    };" newline ...
"" newline ...
"    n = numel(required_files);" newline ...
"    item = cell(n,1);" newline ...
"    path = cell(n,1);" newline ...
"    exists_flag = false(n,1);" newline ...
"    status = cell(n,1);" newline ...
"" newline ...
"    for k = 1:n" newline ...
"        item{k} = required_labels{k};" newline ...
"        path{k} = required_files{k};" newline ...
"        exists_flag(k) = isfile(required_files{k});" newline ...
"        if exists_flag(k)" newline ...
"            status{k} = 'PASS';" newline ...
"        else" newline ...
"            status{k} = 'FAIL';" newline ...
"        end" newline ...
"    end" newline ...
"" newline ...
"    T_files = table(item, path, exists_flag, status, ..." newline ...
"        'VariableNames', {'item','path','exists','status'});" newline ...
"" newline ...
"    correctedFile = fullfile(rootDir,'02_src_limpio','wrappers','opt_tunel_mod2_v10_energy_mode_corrected.m');" newline ...
"    txt = fileread(correctedFile);" newline ...
"" newline ...
"    rule_checks = {" newline ...
"        'gasLP_irradiance_zero',     'gasLP: I_effective = 0'" newline ...
"        'hybrid_irradiance_raw',     'hybrid: I_effective = I_busc'" newline ...
"        'solar_irradiance_raw',      'solar: I_effective = I_busc'" newline ...
"        'gasLP_aux_true',            'gasLP: calor_aux = true'" newline ...
"        'hybrid_aux_true',           'hybrid: calor_aux = true'" newline ...
"        'solar_aux_false',           'solar: calor_aux = false'" newline ...
"        'mode_nargin_patch',         'nargin < 14'" newline ...
"    };" newline ...
"" newline ...
"    m = size(rule_checks,1);" newline ...
"    rule_item = cell(m,1);" newline ...
"    rule_pattern = cell(m,1);" newline ...
"    rule_found = false(m,1);" newline ...
"    rule_status = cell(m,1);" newline ...
"" newline ...
"    for k = 1:m" newline ...
"        rule_item{k} = rule_checks{k,1};" newline ...
"        rule_pattern{k} = rule_checks{k,2};" newline ...
"        rule_found(k) = contains(txt, rule_checks{k,2});" newline ...
"        if rule_found(k)" newline ...
"            rule_status{k} = 'PASS';" newline ...
"        else" newline ...
"            rule_status{k} = 'FAIL';" newline ...
"        end" newline ...
"    end" newline ...
"" newline ...
"    T_rules = table(rule_item, rule_pattern, rule_found, rule_status, ..." newline ...
"        'VariableNames', {'item','pattern','found','status'});" newline ...
"" newline ...
"    diag1 = test_hybrid_irradiance_modes_v10();" newline ...
"    diag2 = test_hybrid_irradiance_modes_v10_robustness();" newline ...
"    report_compare = compare_operation_modes();" newline ...
"" newline ...
"    diagnostic_item = {" newline ...
"        'test_hybrid_irradiance_modes_v10'" newline ...
"        'test_hybrid_irradiance_modes_v10_robustness'" newline ...
"        'compare_operation_modes'" newline ...
"    };" newline ...
"" newline ...
"    diagnostic_status = {" newline ...
"        diag1.status" newline ...
"        diag2.status" newline ...
"        report_compare.status" newline ...
"    };" newline ...
"" newline ...
"    diagnostic_expected = {" newline ...
"        'PASS'" newline ...
"        'PASS'" newline ...
"        'COMPARISON_ONLY_NO_GA'" newline ...
"    };" newline ...
"" newline ...
"    diagnostic_pass = false(3,1);" newline ...
"    for k = 1:3" newline ...
"        diagnostic_pass(k) = strcmp(diagnostic_status{k}, diagnostic_expected{k});" newline ...
"    end" newline ...
"" newline ...
"    T_diag = table(diagnostic_item, diagnostic_status, diagnostic_expected, diagnostic_pass, ..." newline ...
"        'VariableNames', {'item','status','expected','pass'});" newline ...
"" newline ...
"    all_files_ok = all(strcmp(T_files.status,'PASS'));" newline ...
"    all_rules_ok = all(strcmp(T_rules.status,'PASS'));" newline ...
"    all_diag_ok  = all(T_diag.pass);" newline ...
"" newline ...
"    if all_files_ok && all_rules_ok && all_diag_ok" newline ...
"        final_status = 'READY_FOR_PRODUCTIVE_RUN_CONFIGURATION';" newline ...
"    else" newline ...
"        final_status = 'NOT_READY';" newline ...
"    end" newline ...
"" newline ...
"    txtFile = fullfile(logDir,'PRODUCTIVE_RUN_CONTROL_v68.txt');" newline ...
"    csvFiles = fullfile(tabDir,'PRODUCTIVE_RUN_CONTROL_FILES_v68.csv');" newline ...
"    csvRules = fullfile(tabDir,'PRODUCTIVE_RUN_CONTROL_RULES_v68.csv');" newline ...
"    csvDiag  = fullfile(tabDir,'PRODUCTIVE_RUN_CONTROL_DIAGNOSTICS_v68.csv');" newline ...
"    matFile = fullfile(compDir,'PRODUCTIVE_RUN_CONTROL_v68.mat');" newline ...
"" newline ...
"    writetable(T_files,csvFiles);" newline ...
"    writetable(T_rules,csvRules);" newline ...
"    writetable(T_diag,csvDiag);" newline ...
"" newline ...
"    control = struct();" newline ...
"    control.created_at = datetime('now');" newline ...
"    control.created_by_function = 'productive_run_control_v68';" newline ...
"    control.status = final_status;" newline ...
"    control.files_ok = all_files_ok;" newline ...
"    control.rules_ok = all_rules_ok;" newline ...
"    control.diagnostics_ok = all_diag_ok;" newline ...
"    control.txtFile = txtFile;" newline ...
"    control.csvFiles = csvFiles;" newline ...
"    control.csvRules = csvRules;" newline ...
"    control.csvDiagnostics = csvDiag;" newline ...
"    control.matFile = matFile;" newline ...
"" newline ...
"    save(matFile,'control','T_files','T_rules','T_diag');" newline ...
"" newline ...
"    fid = fopen(txtFile,'w');" newline ...
"    fprintf(fid,'PRODUCTIVE_RUN_CONTROL_v68\n\n');" newline ...
"    fprintf(fid,'status: %s\n\n', final_status);" newline ...
"    fprintf(fid,'Scope:\n');" newline ...
"    fprintf(fid,'Pre-run control only.\n');" newline ...
"    fprintf(fid,'GA not executed.\n');" newline ...
"    fprintf(fid,'Long sweeps not executed.\n');" newline ...
"    fprintf(fid,'Costs not modified.\n');" newline ...
"    fprintf(fid,'Final article figures not declared.\n\n');" newline ...
"    fprintf(fid,'Required productive rule:\n');" newline ...
"    fprintf(fid,'gasLP  -> I_effective = 0,      calor_aux = true\n');" newline ...
"    fprintf(fid,'hybrid -> I_effective = I_busc, calor_aux = true\n');" newline ...
"    fprintf(fid,'solar  -> I_effective = I_busc, calor_aux = false\n\n');" newline ...
"    fprintf(fid,'Do not reuse as final:\n');" newline ...
"    fprintf(fid,'historical Fig. 20\n');" newline ...
"    fprintf(fid,'historical Fig. 21\n');" newline ...
"    fprintf(fid,'historical hybrid GA results\n');" newline ...
"    fclose(fid);" newline ...
"" newline ...
"    disp('=== PRODUCTIVE_RUN_CONTROL_v68 ===')" newline ...
"    disp(control.status)" newline ...
"    disp('=== FILE CHECKS ===')" newline ...
"    disp(T_files)" newline ...
"    disp('=== RULE CHECKS ===')" newline ...
"    disp(T_rules)" newline ...
"    disp('=== DIAGNOSTIC CHECKS ===')" newline ...
"    disp(T_diag)" newline ...
"end" newline ...
];

fid = fopen(file,'w');
fprintf(fid,'%s',char(code));
fclose(fid);

clear productive_run_control_v68
rehash

disp('productive_run_control_v68.m reconstruido.')
which productive_run_control_v68 -all