function result=run_pe07_controlled_sensitivity(confirm_execute,authorization)
% Future PE07 execution runner. Infrastructure tests must never invoke this.
if nargin<1 || ~isequal(confirm_execute,true)
    error('PE07:ExecutionLocked','Explicit execution authorization required.');
end
if nargin~=2 || ~isstruct(authorization)
    error('PE07:Authorization','Authorization record required.');
end
required={'approved','gate','campaign_id','expected_head','config_sha256', ...
    'protocol_sha256','record'};
assert(all(isfield(authorization,required)) && isequal(authorization.approved,true), ...
    'PE07:Authorization','Incomplete or unapproved authorization.');
assert(strcmp(authorization.gate,'ROR_PE_07_BASELINE_REPLAY_EXECUTION_AUTHORIZATION') && ...
    strcmp(authorization.campaign_id,'ROR_PE07_CONTROLLED_SENSITIVITY_V01') && ...
    ~isempty(authorization.record),'PE07:Authorization','Wrong authorization gate.');

here=fileparts(mfilename('fullpath'));
repoRoot=fileparts(fileparts(fileparts(fileparts(here))));
assert(strcmpi(canonical(pwd),canonical(repoRoot)), ...
    'PE07:Repository','Start runner from repository root.');
configPath=fullfile(here,'pe07_controlled_sensitivity_config.json');
cfg=jsondecode(fileread(configPath));
assert(strcmp(authorization.config_sha256, ...
    pe07_execution_guard('file_hash',configPath)) && ...
    strcmp(authorization.protocol_sha256,cfg.protocol_sha256), ...
    'PE07:Authorization','Authorized config/protocol hash mismatch.');

[ok,observedHead]=system('git rev-parse HEAD');
assert(ok==0 && strcmpi(strtrim(observedHead),authorization.expected_head), ...
    'PE07:Git','Observed HEAD differs from final authorized infrastructure HEAD.');
[ok,statusText]=system('git status --porcelain --untracked-files=no');
assert(ok==0 && isempty(strtrim(statusText)), ...
    'PE07:Git','Tracked worktree or staging is not clean.');
observedHead=strtrim(observedHead);

executionRoot=fullfile(repoRoot,cfg.execution_root);
plan=pe07_execution_guard('validate_config',cfg,repoRoot,executionRoot);
lockPath=fullfile(here,'pe07_execution_source_lock.json');
lock=jsondecode(fileread(lockPath));
pe07_execution_guard('verify_lock',repoRoot,lock);
assert(strcmp(pe07_execution_guard('file_hash', ...
    fullfile(repoRoot,cfg.productive_source_lock_path)), ...
    cfg.productive_source_lock_sha256),'PE07:ProductiveLock','Productive lock changed.');

assert(cfg.budget.baseline_replays+cfg.budget.valid_perturbations==50 && ...
    cfg.budget.max_executable==50 && cfg.budget.absolute_structural_cap==51, ...
    'PE07:Budget','Executable budget mismatch.');
assert(sum([cfg.conditions.evaluate])==47,'PE07:Budget','Valid condition count mismatch.');

addpath(fullfile(repoRoot,'02_src_limpio','main'));
assert(strcmpi(canonical(which('setup_v05_paths')), ...
    canonical(fullfile(repoRoot,'02_src_limpio','main','setup_v05_paths.m'))), ...
    'PE07:Shadow','setup_v05_paths shadowed.');
setup_v05_paths();
addpath(genpath(fullfile(repoRoot,'02_src_limpio')));
assert(strcmpi(canonical(which(cfg.objective_entry_point)),canonical(fullfile(repoRoot, ...
    '02_src_limpio','production',[cfg.objective_entry_point '.m']))), ...
    'PE07:Shadow','Productive objective shadowed.');
pe07_execution_guard('verify_lock',repoRoot,lock);

global TRACE_V628B_DIR TRACE_V628B_MODE TRACE_V628B_TAG
TRACE_V628B_DIR=[]; TRACE_V628B_MODE=[]; TRACE_V628B_TAG=[];

pe07_execution_guard('reserve_root',executionRoot);
startStamp=utc_stamp();
initialProvenance=struct('schema',1,'status','ROOT_RESERVED_BASELINE_PENDING', ...
    'campaign_id',cfg.campaign_id,'design_version',cfg.design_version, ...
    'git_head',observedHead,'upstream_canonical_baseline_head', ...
    cfg.upstream_canonical_baseline_head,'start_timestamp',startStamp, ...
    'matlab_version',version,'matlab_release',version('-release'), ...
    'platform',computer,'config_sha256',authorization.config_sha256, ...
    'protocol_sha256',cfg.protocol_sha256,'pe07_source_lock_sha256', ...
    pe07_execution_guard('file_hash',lockPath), ...
    'productive_source_lock_sha256',cfg.productive_source_lock_sha256, ...
    'authorization',authorization,'guard_plan',plan,'use_parallel',false, ...
    'trace_globals_cleared',true);
pe07_execution_guard('write_text_once',fullfile(executionRoot, ...
    'FROZEN_PE07_CONFIG.json'),fileread(configPath));
write_anchor_csv(fullfile(executionRoot,'ANCHOR_SELECTION_TABLE.csv'),cfg.anchors);
write_condition_csv(fullfile(executionRoot,'PROPOSED_EVALUATION_MATRIX.csv'),cfg.conditions);
domainAudit=struct('status','PASS','structural_conditions',48, ...
    'preclassified_out_of_domain',1,'valid_perturbations',47, ...
    'out_of_domain_condition_ids',{{'P001_N21_m_max_minus_large'}}, ...
    'clipping','PROHIBITED','substitution','PROHIBITED');
pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
    'DOMAIN_AUDIT_PREEXECUTION.json'),domainAudit);
pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
    'EXECUTION_PROVENANCE_INITIAL.json'),initialProvenance);

baselineRecords=repmat(empty_record(),1,3);
perturbationRecords=repmat(empty_record(),1,0);
invalidInventory=struct('condition_id','P001_N21_m_max_minus_large', ...
    'classification','OUT_OF_DOMAIN_PREDEFINED_PERTURBATION', ...
    'evaluated',false,'retained_in_audit',true, ...
    'excluded_from_finite_differences',true);
try
    for k=1:3
        a=cfg.anchors(k);
        conditionId=sprintf('B%03d_%s',k,a.anchor_id);
        baselineRecords(k)=evaluate_one(conditionId,k,'BASELINE',a.anchor_id, ...
            double(a.x(:)'),cfg);
        baselineRecords(k).baseline_exact_match=exact_baseline_match( ...
            baselineRecords(k).responses,a.expected,cfg.baseline_exact_fields);
    end
    baselineMatches=[baselineRecords.baseline_exact_match];
    gate=pe07_execution_guard('baseline_gate',baselineMatches, ...
        cfg.budget.valid_perturbations);
    baselineAudit=struct('status',gate.status,'pass_count',gate.baseline_pass_count, ...
        'required_count',3,'exact_rule',cfg.baseline_pass_rule, ...
        'records',baselineRecords,'timestamps_excluded',true, ...
        'tolerance_fallback','PROHIBITED');
    pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
        'BASELINE_REPLAY_AUDIT.json'),baselineAudit);

    if ~gate.all_pass
        pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
            'PERTURBATION_RESULTS.json'),struct('status','NOT_RUN_BASELINE_MISMATCH', ...
            'evaluation_count',0,'records',[]));
        pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
            'INVALID_POINT_INVENTORY.json'),invalidInventory);
        finalProvenance=finalize_provenance(initialProvenance, ...
            'BASELINE_REPLAY_MISMATCH',0,utc_stamp());
        pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
            'EXECUTION_PROVENANCE.json'),finalProvenance);
        pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
            'EXECUTION_STATUS.json'),struct('status','BASELINE_REPLAY_MISMATCH', ...
            'baseline_pass_count',gate.baseline_pass_count, ...
            'perturbation_evaluations',0,'automatic_retry',false));
        write_execution_inventory(executionRoot);
        result=finalProvenance;
        return
    end

    valid=cfg.conditions([cfg.conditions.evaluate]);
    assert(numel(valid)==47 && gate.perturbation_evaluations_authorized==47, ...
        'PE07:Budget','Perturbation gate/count mismatch.');
    perturbationRecords=repmat(empty_record(),1,47);
    for k=1:47
        c=valid(k); anchor=cfg.anchors(strcmp({cfg.anchors.anchor_id},c.anchor_id));
        x=double(anchor.x(:)'); variableIndex=find(strcmp({cfg.variables.name},c.variable));
        x(variableIndex)=c.proposed_value;
        perturbationRecords(k)=evaluate_one(c.condition_id,c.execution_order, ...
            'PERTURBATION',c.anchor_id,x,cfg);
        if perturbationRecords(k).invalid
            invalidInventory(end+1)=struct('condition_id',c.condition_id, ...
                'classification',strjoin(perturbationRecords(k).invalid_reasons,';'), ...
                'evaluated',true,'retained_in_audit',true, ...
                'excluded_from_finite_differences',true); %#ok<AGROW>
        end
    end
    pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
        'PERTURBATION_RESULTS.json'),struct('status','COMPLETED', ...
        'evaluation_count',47,'records',perturbationRecords));
    pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
        'INVALID_POINT_INVENTORY.json'),invalidInventory);
    finalProvenance=finalize_provenance(initialProvenance, ...
        'COMPLETED_PENDING_POSTRUN',47,utc_stamp());
    pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
        'EXECUTION_PROVENANCE.json'),finalProvenance);
    pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
        'EXECUTION_STATUS.json'),struct('status','COMPLETED_PENDING_POSTRUN', ...
        'baseline_pass_count',3,'perturbation_evaluations',47, ...
        'automatic_retry',false));
    write_execution_inventory(executionRoot);
    result=finalProvenance;
catch failure
    evidence=struct('status','FAILED_NO_AUTORETRY','timestamp',utc_stamp(), ...
        'identifier',failure.identifier,'message',failure.message, ...
        'baseline_records',baselineRecords,'perturbation_records',perturbationRecords, ...
        'automatic_retry',false);
    try pe07_execution_guard('write_json_once',fullfile(executionRoot, ...
            'FAILURE_EVIDENCE.json'),evidence); catch, end
    rethrow(failure);
end
end

function record=evaluate_one(conditionId,order,kind,anchorId,x,cfg)
record=empty_record(); record.condition_id=conditionId; record.execution_order=order;
record.kind=kind; record.anchor_id=anchorId; record.x=x; record.started_at=utc_stamp();
try
    [f,detail]=objective_productive_corrected_v96j_triobjective_CO2_fix1(x,cfg.mode_operation);
    record.f=double(f(:)'); record.status=char(string(detail.status));
    record.execution_status=char(string(detail.execution_status));
    record.responses=extract_responses(record.f,detail);
catch failure
    record.error_identifier=failure.identifier; record.error_message=failure.message;
    record.status='CAUGHT_EVALUATION_ERROR'; record.execution_status='ERROR';
end
record.completed_at=utc_stamp();
classification=pe07_execution_guard('classify_result',record,cfg);
record.invalid=classification.invalid; record.invalid_reasons=classification.reasons;
record.eligible_for_finite_difference=classification.eligible_for_finite_difference;
end

function responses=extract_responses(f,detail)
responses=struct('MR',double(detail.objectives.MR_final), ...
    'W',double(detail.cost.water_removed_kg), ...
    'Q_aux_useful_MJ',double(detail.cost.Q_aux_useful_MJ), ...
    'LPG_fuel_input_MJ',double(detail.cost.LPG_fuel_input_MJ), ...
    'f1',double(f(1)),'f2',double(f(2)),'f3',double(f(3)));
end

function pass=exact_baseline_match(observed,expected,fields)
pass=true;
for k=1:numel(fields)
    name=fields{k};
    pass=pass && isfield(observed,name) && isfield(expected,name) && ...
        isequal(observed.(name),expected.(name));
end
end

function record=empty_record()
record=struct('condition_id','','execution_order',0,'kind','','anchor_id','', ...
    'x',[],'f',[],'status','UNINITIALIZED','execution_status','UNINITIALIZED', ...
    'responses',struct(),'error_identifier','','error_message','', ...
    'invalid',true,'invalid_reasons',{{}},'eligible_for_finite_difference',false, ...
    'baseline_exact_match',false,'started_at','','completed_at','');
end

function value=finalize_provenance(initial,status,count,endStamp)
value=initial; value.status=status; value.end_timestamp=endStamp;
value.perturbation_evaluations=count; value.automatic_retry=false;
end

function write_anchor_csv(path,anchors)
lines="anchor_id,context,baseline_order,n_pool_row,seed,source,source_row,x1,x2,x3,x4,f1,f2,f3,MR,W,Q_aux_useful_MJ,LPG_fuel_input_MJ"+newline;
for k=1:numel(anchors)
    a=anchors(k);
    row=sprintf('%s,%s,%d,%d,%d,%s,%d',a.anchor_id,a.context, ...
        a.baseline_order,a.n_pool_row,a.seed,a.source,a.source_row);
    values=[a.x(:)' a.f(:)' a.expected.MR a.expected.W ...
        a.expected.Q_aux_useful_MJ a.expected.LPG_fuel_input_MJ];
    lines=lines+string(row)+sprintf(',%.17g',values)+newline;
end
pe07_execution_guard('write_text_once',path,char(lines));
end

function write_condition_csv(path,conditions)
lines="condition_id,execution_order,anchor_id,variable,direction,magnitude,delta,proposed_value,domain_status,evaluate"+newline;
for k=1:numel(conditions)
    c=conditions(k);
    row=sprintf('%s,%d,%s,%s,%s,%s,%.17g,%.17g,%s,%d', ...
        c.condition_id,c.execution_order,c.anchor_id,c.variable,c.direction, ...
        c.magnitude,c.delta,c.proposed_value,c.domain_status,c.evaluate);
    lines=lines+string(row)+newline;
end
pe07_execution_guard('write_text_once',path,char(lines));
end

function write_execution_inventory(root)
files=dir(root); inventory=struct('path',{},'sha256',{},'size',{});
for k=1:numel(files)
    if files(k).isdir || strcmp(files(k).name,'SHA256_MANIFEST_EXECUTION.json'), continue, end
    inventory(end+1)=struct('path',files(k).name, ...
        'sha256',pe07_execution_guard('file_hash',fullfile(root,files(k).name)), ...
        'size',files(k).bytes); %#ok<AGROW>
end
pe07_execution_guard('write_json_once',fullfile(root, ...
    'SHA256_MANIFEST_EXECUTION.json'),inventory);
end

function stamp=utc_stamp()
stamp=char(datetime('now','TimeZone','UTC','Format',"yyyy-MM-dd'T'HH:mm:ss.SSSXXX"));
end

function value=canonical(path)
value=char(java.io.File(path).getCanonicalPath());
end
