function plan=ror_extended_diagnostic_guards(cfg,primaryCfg,repoRoot,executionRoot,warmStart)
% Fail-closed validation for the single secondary 61001x400 diagnostic.
assert(isstruct(cfg) && isstruct(primaryCfg),'ROR:DiagnosticConfig','Configs required.');
assert(strcmp(cfg.campaign_id,'ROR_BUDGET_DIAGNOSTIC_61001_G400_V01') && ...
    strcmp(cfg.role,'SECONDARY_EXTENDED_BUDGET_DIAGNOSTIC'), ...
    'ROR:DiagnosticIdentity','Wrong diagnostic identity.');
assert(cfg.seed==61001,'ROR:DiagnosticSeed','Only seed 61001 is authorized.');
assert(cfg.nvars==4,'ROR:DiagnosticNvars','NVARS must be four.');
assert(strcmp(cfg.initialization,'FROM_SCRATCH') && ...
    ~cfg.warm_starts.HB200 && ~cfg.warm_starts.C && ...
    ~cfg.warm_starts.PRIMARY_200GEN && isempty(warmStart), ...
    'ROR:DiagnosticWarmStart','All warm starts are prohibited.');
assert(cfg.options.PopulationSize==24,'ROR:DiagnosticPopulation','PopulationSize must be 24.');
assert(cfg.options.MaxGenerations==400,'ROR:DiagnosticGenerations','MaxGenerations must be 400.');
assert(isequal(cfg.options.UseParallel,false),'ROR:DiagnosticParallel','UseParallel must be false.');
assert(isempty(cfg.options.InitialPopulationMatrix), ...
    'ROR:DiagnosticInitialPopulation','InitialPopulationMatrix must be empty.');
assert(isempty(cfg.options.InitialScoresMatrix), ...
    'ROR:DiagnosticInitialScores','InitialScoresMatrix must be empty.');
assert(strcmp(cfg.snapshot_output_fcn,'ror_extended_snapshot_outputfcn') && ...
    strcmp(cfg.options.OutputFcn,'ror_extended_snapshot_outputfcn'), ...
    'ROR:DiagnosticOutputFcn','Wrong diagnostic OutputFcn.');
assert(isequal(double(cfg.snapshot_generations(:)'),50:50:400), ...
    'ROR:DiagnosticCheckpoints','Checkpoint schedule mismatch.');

expected=primaryCfg.options;
expected.MaxGenerations=400;
expected.OutputFcn='ror_extended_snapshot_outputfcn';
[same,~,~]=ror_options_equivalent(expected,cfg.options);
assert(same,'ROR:DiagnosticScientificDifference', ...
    'Unexpected option difference from primary configuration.');
assert(primaryCfg.nvars==4 && isequal(double(primaryCfg.lb(:)'),double(cfg.lb(:)')) && ...
    isequal(double(primaryCfg.ub(:)'),double(cfg.ub(:)')) && ...
    strcmp(primaryCfg.objective,cfg.objective) && strcmp(primaryCfg.mode,cfg.mode), ...
    'ROR:DiagnosticScientificDifference','Unexpected scientific configuration difference.');

assert(strcmp(ror_guard_hash(fullfile(repoRoot,cfg.protocol_path)),cfg.protocol_sha256), ...
    'ROR:DiagnosticProtocolHash','Protocol/hash mismatch.');
assert(strcmp(ror_guard_hash(fullfile(repoRoot,cfg.primary_config_path)), ...
    cfg.primary_config_sha256),'ROR:DiagnosticPrimaryConfigHash','Primary config/hash mismatch.');
assert(strcmp(ror_guard_hash(fullfile(repoRoot,cfg.primary_reference_path)), ...
    cfg.primary_reference_sha256),'ROR:DiagnosticPrimaryHash','Primary reference/hash mismatch.');

expectedRoot=fullfile(repoRoot,cfg.output_root,cfg.campaign_id);
assert(strcmpi(canonical(executionRoot),canonical(expectedRoot)), ...
    'ROR:DiagnosticPath','Execution root differs from frozen diagnostic root.');
primaryRoot=fullfile(repoRoot,'05_runs','robust_operating_region_v01', ...
    'ROR_PRIMARY_20260907_REAUTHORIZED');
assert(~startsWith([lower(canonical(executionRoot)) filesep], ...
    [lower(canonical(primaryRoot)) filesep]), ...
    'ROR:DiagnosticPrimaryPath','Writing under primary outputs is prohibited.');
ror_extended_root_guard(executionRoot);

plan=struct('status','PASS','campaign_id',cfg.campaign_id,'seed',cfg.seed, ...
    'nvars',cfg.nvars,'execution_root',executionRoot, ...
    'authorized_scientific_difference','MaxGenerations: 200 -> 400', ...
    'authorized_observational_difference', ...
    'OutputFcn: [] -> ror_extended_snapshot_outputfcn');
end

function value=canonical(path)
value=char(java.io.File(path).getCanonicalPath());
end

function h=ror_guard_hash(path)
fid=fopen(path,'rb'); assert(fid>=0,'ROR:DiagnosticFile','Cannot read %s',path);
cleanup=onCleanup(@()fclose(fid));
md=java.security.MessageDigest.getInstance('SHA-256');
while ~feof(fid), md.update(fread(fid,1048576,'*uint8')); end
h=upper(reshape(dec2hex(typecast(md.digest(),'uint8'),2)',1,[]));
end
