function plan = ror_recovery_guards(cfg,recovery_seeds,warm_start)
% Pure fail-closed recovery-plan validation. Performs no IO or evaluations.
original_seeds = [61001 61002];
expected_recovery = [61003 61004 61005];
final_seeds = 61001:61005;

assert(isnumeric(recovery_seeds) && isvector(recovery_seeds) && ...
    all(isfinite(recovery_seeds)) && all(recovery_seeds==fix(recovery_seeds)), ...
    'ROR:RecoverySeeds','Recovery seeds must be finite integers.');
recovery_seeds = double(recovery_seeds(:)');
assert(numel(unique(recovery_seeds))==numel(recovery_seeds), ...
    'ROR:RecoveryDuplicateSeed','Duplicate recovery seed.');
assert(all(ismember(recovery_seeds,final_seeds)), ...
    'ROR:RecoveryUnknownSeed','Recovery seed outside the frozen five-seed set.');
assert(isempty(intersect(recovery_seeds,original_seeds)), ...
    'ROR:RecoveryOriginalSeed','Completed original seeds cannot be reexecuted.');
assert(isequal(recovery_seeds,expected_recovery), ...
    'ROR:RecoverySubset','Recovery seeds must be exactly 61003, 61004, 61005.');
assert(isempty(intersect(original_seeds,recovery_seeds)) && ...
    isequal(sort([original_seeds recovery_seeds]),final_seeds), ...
    'ROR:RecoveryIdentity','Final primary identity must be exactly five unique seeds.');

assert(isstruct(cfg) && isequal(double(cfg.seeds(:)'),final_seeds) && ...
    cfg.primary_run_count==5 && cfg.nvars==4, ...
    'ROR:RecoveryConfig','Frozen seed/count/nvars configuration mismatch.');
assert(~cfg.HB200_INITIALIZATION && ~cfg.C_INITIALIZATION && ...
    ~cfg.execution_authorized, ...
    'ROR:RecoveryWarmStart','Frozen configuration permits initialization/execution.');
assert(cfg.options.PopulationSize==24 && cfg.options.MaxGenerations==200 && ...
    isequal(cfg.options.UseParallel,false), ...
    'ROR:RecoveryConfig','Scientific solver configuration mismatch.');
assert(isempty(cfg.options.InitialPopulationMatrix) && ...
    isempty(cfg.options.InitialScoresMatrix), ...
    'ROR:RecoveryWarmStart','Initial population/scores must be empty.');
assert(isempty(warm_start), ...
    'ROR:RecoveryWarmStart','Warm start, partial path, population, scores or RNG are prohibited.');

plan=struct('original_valid_seeds',original_seeds, ...
    'recovery_seeds',expected_recovery,'final_primary_seed_set',final_seeds, ...
    'interrupted_seed',61003,'interrupted_attempt_class','INTERRUPTED_ATTEMPT_EVIDENCE');
end
